package formularios;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import jctablecheckdel.Celda_CheckBox;
import jctablecheckdel.Render_CheckBox;
import clases.SQL;
import clases.listas.estArticulo;
import clases.listas.estReparacion;
import clases.listas.estUsuario;
import clases.listas.estComponente;
import java.io.*;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import clases.listas.estArticulo;
import static formularios.IfrmCrudArticulos.cab;

public class IfrmSolicitud extends javax.swing.JInternalFrame {

    SQL sql = new SQL();
    static Object[] codigos;
    validacionesCampos validar = new validacionesCampos();
    static estReparacion cab = null, ult = null;
    static estUsuario cabUsu = null, ultUsu = null;
    static estArticulo cabArt = null, ultArt = null;
    static estComponente cabcomp = null, ultcomp = null;

    public IfrmSolicitud() {

        initComponents();
        formColores("FFFFFF", "6699ff", "FFFFFF");
        tbpSolicitud.setTabPlacement(tbpSolicitud.BOTTOM);

        txtDocSolicitante.requestFocus();
        camposSolicitante();
        pestanhas(true, false, false);
        camposComponentes();

        cargarUsuarios();
        cargarArticulos();
        cargarComponente();
        cargarDatos();
        botones(false);

    }

    IfrmSolicitud(estUsuario DatosU) {
        initComponents();
        formColores("FFFFFF", "6699ff", "FFFFFF");
        tbpSolicitud.setTabPlacement(tbpSolicitud.BOTTOM);

        txtDocSolicitante.requestFocus();
        txtcodigo1.requestFocus();
        camposSolicitante();
        camposComponentes();
        camposAgenda();
        pestanhas(true, false, false);
       

        cargarUsuarios();
        cargarArticulos();
        cargarComponente();
        cargarDatos(); //To change body of generated methods, choose Tools | Templates.

        txtDocSolicitante.setText(DatosU.usuario);
        llenarSolicitud();
    }

  
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        tbpSolicitud = new javax.swing.JTabbedPane();
        pnlSolicitante = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbDocSolicitante = new javax.swing.JLabel();
        txtDocSolicitante = new javax.swing.JTextField();
        separaSolici = new javax.swing.JSeparator();
        lbNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        lbApellidos = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        lbPerfil = new javax.swing.JLabel();
        txtPerfil = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        lbEstado = new javax.swing.JLabel();
        btnDocumento = new javax.swing.JButton();
        pnlBotonesSolicitante = new javax.swing.JPanel();
        btnCanceRegisSolic = new javax.swing.JButton();
        btnRegisSolici = new javax.swing.JButton();
        btnCambiarSolici = new javax.swing.JButton();
        pnlArticulo = new javax.swing.JPanel();
        pnlTituloArt = new javax.swing.JPanel();
        lbTituloArt = new javax.swing.JLabel();
        lbNumSerie = new javax.swing.JLabel();
        txtcodigo1 = new javax.swing.JTextField();
        separaArt = new javax.swing.JSeparator();
        btnCodigo = new javax.swing.JButton();
        btnCambiarCam = new javax.swing.JButton();
        lbTipo1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lbTipo2 = new javax.swing.JLabel();
        lbTipo3 = new javax.swing.JLabel();
        lbTipo4 = new javax.swing.JLabel();
        pnlBotonesSolicitante1 = new javax.swing.JPanel();
        btnRegiscomp = new javax.swing.JButton();
        btnCanceRegisComp = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox();
        cmbacceso = new javax.swing.JComboBox();
        cmbPro = new javax.swing.JComboBox();
        pnlSolicitud = new javax.swing.JPanel();
        pnlTituloSoli = new javax.swing.JPanel();
        lbTituloSoli = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        lbNumSerie1 = new javax.swing.JLabel();
        lbTipo5 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtEstado1 = new javax.swing.JTextField();
        lbNumSerie2 = new javax.swing.JLabel();
        txtFe = new javax.swing.JTextField();
        TxtHT = new javax.swing.JTextField();
        txtHoraI = new javax.swing.JTextField();
        lbFecha = new javax.swing.JLabel();
        lbEstado1 = new javax.swing.JLabel();
        lbModelo = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        tbpSolicitud.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        tbpSolicitud.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tbpSolicitudMouseMoved(evt);
            }
        });

        pnlSolicitante.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlSolicitanteMouseMoved(evt);
            }
        });

        pnlTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloMouseMoved(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        lbTitulo.setText("Solicitante");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbDocSolicitante.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbDocSolicitante.setText("*Documento");

        txtDocSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocSolicitanteActionPerformed(evt);
            }
        });
        txtDocSolicitante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocSolicitanteKeyTyped(evt);
            }
        });

        separaSolici.setForeground(new java.awt.Color(0, 0, 0));

        lbNombres.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbNombres.setText("*Nombres");

        lbApellidos.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbApellidos.setText("*Apellidos");

        lbEmail.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbEmail.setText("*E-mail");

        lbPerfil.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbPerfil.setText("*Perfil");

        lbEstado.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbEstado.setText("*Estado");

        btnDocumento.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnDocumento.setText("Aceptar");
        btnDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentoActionPerformed(evt);
            }
        });

        pnlBotonesSolicitante.setBackground(new java.awt.Color(255, 255, 255));

        btnCanceRegisSolic.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnCanceRegisSolic.setText("Cancelar");
        btnCanceRegisSolic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanceRegisSolicActionPerformed(evt);
            }
        });

        btnRegisSolici.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnRegisSolici.setText("Registrar");
        btnRegisSolici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisSoliciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesSolicitanteLayout = new javax.swing.GroupLayout(pnlBotonesSolicitante);
        pnlBotonesSolicitante.setLayout(pnlBotonesSolicitanteLayout);
        pnlBotonesSolicitanteLayout.setHorizontalGroup(
            pnlBotonesSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesSolicitanteLayout.createSequentialGroup()
                .addComponent(btnRegisSolici)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCanceRegisSolic)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlBotonesSolicitanteLayout.setVerticalGroup(
            pnlBotonesSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesSolicitanteLayout.createSequentialGroup()
                .addGroup(pnlBotonesSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisSolici)
                    .addComponent(btnCanceRegisSolic))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        btnCambiarSolici.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnCambiarSolici.setText("Cambiar");
        btnCambiarSolici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarSoliciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSolicitanteLayout = new javax.swing.GroupLayout(pnlSolicitante);
        pnlSolicitante.setLayout(pnlSolicitanteLayout);
        pnlSolicitanteLayout.setHorizontalGroup(
            pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(separaSolici)
            .addGroup(pnlSolicitanteLayout.createSequentialGroup()
                .addGroup(pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSolicitanteLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSolicitanteLayout.createSequentialGroup()
                                .addComponent(lbNombres)
                                .addGap(8, 8, 8)
                                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSolicitanteLayout.createSequentialGroup()
                                .addGroup(pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbApellidos)
                                    .addComponent(lbEmail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail)
                                    .addComponent(txtApellidos))))
                        .addGap(32, 32, 32)
                        .addGroup(pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSolicitanteLayout.createSequentialGroup()
                                .addComponent(lbPerfil)
                                .addGap(18, 18, 18)
                                .addComponent(txtPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlSolicitanteLayout.createSequentialGroup()
                                .addComponent(lbEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlBotonesSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlSolicitanteLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbDocSolicitante)
                        .addGap(18, 18, 18)
                        .addComponent(txtDocSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCambiarSolici)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSolicitanteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtApellidos, txtNombres});

        pnlSolicitanteLayout.setVerticalGroup(
            pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolicitanteLayout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDocSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDocumento)
                        .addComponent(btnCambiarSolici))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitanteLayout.createSequentialGroup()
                        .addComponent(lbDocSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addComponent(separaSolici, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSolicitanteLayout.createSequentialGroup()
                        .addGroup(pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlSolicitanteLayout.createSequentialGroup()
                        .addGroup(pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlBotonesSolicitante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbpSolicitud.addTab("Solicitante", pnlSolicitante);

        pnlArticulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlArticuloMouseMoved(evt);
            }
        });

        pnlTituloArt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloArtMouseMoved(evt);
            }
        });

        lbTituloArt.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        lbTituloArt.setText("Expediente");

        javax.swing.GroupLayout pnlTituloArtLayout = new javax.swing.GroupLayout(pnlTituloArt);
        pnlTituloArt.setLayout(pnlTituloArtLayout);
        pnlTituloArtLayout.setHorizontalGroup(
            pnlTituloArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloArtLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(lbTituloArt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloArtLayout.setVerticalGroup(
            pnlTituloArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloArtLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloArt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbNumSerie.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbNumSerie.setText("*codigo");

        txtcodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigo1ActionPerformed(evt);
            }
        });
        txtcodigo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigo1KeyTyped(evt);
            }
        });

        separaArt.setForeground(new java.awt.Color(0, 0, 0));

        btnCodigo.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnCodigo.setText("Aceptar");
        btnCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodigoActionPerformed(evt);
            }
        });

        btnCambiarCam.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnCambiarCam.setText("Cambiar");
        btnCambiarCam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarCamActionPerformed(evt);
            }
        });

        lbTipo1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbTipo1.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        lbTipo2.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbTipo2.setText("Proceso");

        lbTipo3.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbTipo3.setText("TipoExp");

        lbTipo4.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbTipo4.setText("Acceso");

        pnlBotonesSolicitante1.setBackground(new java.awt.Color(255, 255, 255));

        btnRegiscomp.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnRegiscomp.setText("Registrar");
        btnRegiscomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegiscompActionPerformed(evt);
            }
        });

        btnCanceRegisComp.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnCanceRegisComp.setText("Cancelar");
        btnCanceRegisComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanceRegisCompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesSolicitante1Layout = new javax.swing.GroupLayout(pnlBotonesSolicitante1);
        pnlBotonesSolicitante1.setLayout(pnlBotonesSolicitante1Layout);
        pnlBotonesSolicitante1Layout.setHorizontalGroup(
            pnlBotonesSolicitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesSolicitante1Layout.createSequentialGroup()
                .addComponent(btnRegiscomp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCanceRegisComp)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlBotonesSolicitante1Layout.setVerticalGroup(
            pnlBotonesSolicitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesSolicitante1Layout.createSequentialGroup()
                .addGroup(pnlBotonesSolicitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegiscomp)
                    .addComponent(btnCanceRegisComp))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un perfil ...", "Judicial", "Extrajudicial", "Consulta","Arbitral" }));
        cmbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoItemStateChanged(evt);
            }
        });
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        cmbacceso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un perfil ...", "Privado", "Publico" }));
        cmbacceso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbaccesoItemStateChanged(evt);
            }
        });
        cmbacceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbaccesoActionPerformed(evt);
            }
        });

        cmbPro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "herencia", "lesiones personales", "conciliacion" }));
        cmbPro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProItemStateChanged(evt);
            }
        });
        cmbPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlArticuloLayout = new javax.swing.GroupLayout(pnlArticulo);
        pnlArticulo.setLayout(pnlArticuloLayout);
        pnlArticuloLayout.setHorizontalGroup(
            pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(separaArt)
            .addGroup(pnlArticuloLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                        .addComponent(lbTipo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                        .addComponent(lbTipo4)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPro, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlArticuloLayout.createSequentialGroup()
                                .addComponent(lbTipo3)
                                .addGap(3, 3, 3))
                            .addComponent(lbTipo2))
                        .addGap(26, 26, 26)
                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTipo, 0, 135, Short.MAX_VALUE)
                            .addComponent(cmbacceso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArticuloLayout.createSequentialGroup()
                        .addComponent(pnlBotonesSolicitante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
            .addGroup(pnlArticuloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNumSerie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambiarCam)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        pnlArticuloLayout.setVerticalGroup(
            pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArticuloLayout.createSequentialGroup()
                .addComponent(pnlTituloArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCodigo)
                        .addComponent(btnCambiarCam))
                    .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbNumSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separaArt, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                        .addComponent(lbTipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbacceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTipo4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addComponent(pnlBotonesSolicitante1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pnlBotonesSolicitante1.getAccessibleContext().setAccessibleParent(pnlBotonesSolicitante1);

        tbpSolicitud.addTab("Expediente", pnlArticulo);

        pnlTituloSoli.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloSoliMouseMoved(evt);
            }
        });

        lbTituloSoli.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        lbTituloSoli.setText("agenda");

        javax.swing.GroupLayout pnlTituloSoliLayout = new javax.swing.GroupLayout(pnlTituloSoli);
        pnlTituloSoli.setLayout(pnlTituloSoliLayout);
        pnlTituloSoliLayout.setHorizontalGroup(
            pnlTituloSoliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSoliLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(lbTituloSoli)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        pnlTituloSoliLayout.setVerticalGroup(
            pnlTituloSoliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloSoliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloSoli, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLugarActionPerformed(evt);
            }
        });
        txtLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLugarKeyTyped(evt);
            }
        });

        lbNumSerie1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbNumSerie1.setText("*Lugar");

        lbTipo5.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbTipo5.setText("Titulo");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTituloKeyTyped(evt);
            }
        });

        txtEstado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstado1ActionPerformed(evt);
            }
        });
        txtEstado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstado1KeyTyped(evt);
            }
        });

        lbNumSerie2.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbNumSerie2.setText("*Estado");

        txtFe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeActionPerformed(evt);
            }
        });

        lbFecha.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbFecha.setText("*Fecha");

        lbEstado1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbEstado1.setText("*Hora terminación");

        lbModelo.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbModelo.setText("*Hora inicio");

        btnNuevo.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSolicitudLayout = new javax.swing.GroupLayout(pnlSolicitud);
        pnlSolicitud.setLayout(pnlSolicitudLayout);
        pnlSolicitudLayout.setHorizontalGroup(
            pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloSoli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlSolicitudLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSolicitudLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlSolicitudLayout.createSequentialGroup()
                            .addComponent(lbNumSerie2)
                            .addGap(18, 18, 18)
                            .addComponent(txtEstado1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addGroup(pnlSolicitudLayout.createSequentialGroup()
                            .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbNumSerie1)
                                .addComponent(lbTipo5))
                            .addGap(24, 24, 24)
                            .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtLugar, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addComponent(txtTitulo))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbFecha)
                        .addComponent(lbEstado1)
                        .addComponent(lbModelo))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtHoraI, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(TxtHT)
                        .addComponent(txtFe))
                    .addGap(42, 42, 42)))
        );
        pnlSolicitudLayout.setVerticalGroup(
            pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitudLayout.createSequentialGroup()
                .addComponent(pnlTituloSoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnRegistrar))
                .addGap(45, 45, 45))
            .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSolicitudLayout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlSolicitudLayout.createSequentialGroup()
                            .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbNumSerie1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbTipo5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(13, 13, 13)
                            .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbNumSerie2)))
                        .addGroup(pnlSolicitudLayout.createSequentialGroup()
                            .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHoraI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(117, Short.MAX_VALUE)))
        );

        tbpSolicitud.addTab("Solicitud", pnlSolicitud);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbpSolicitudMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpSolicitudMouseMoved

    }//GEN-LAST:event_tbpSolicitudMouseMoved

    private void pnlTituloSoliMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSoliMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSoliMouseMoved

    private void pnlArticuloMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlArticuloMouseMoved

    }//GEN-LAST:event_pnlArticuloMouseMoved

    private void btnCanceRegisCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanceRegisCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCanceRegisCompActionPerformed

    private void btnRegiscompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegiscompActionPerformed

        String codigo = txtcodigo1.getText();
        String acceso = cmbacceso.getToolTipText();
        String proceso = cmbPro.getToolTipText();
        String tipoExp = cmbTipo.getToolTipText();
        String nombre = txtNombre.getText();

        String tipo = "";

        if (codigo.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el codigo", "Atención", JOptionPane.ERROR_MESSAGE);
            txtcodigo1.requestFocus();
        } else if (acceso.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de acceso", "Atención", JOptionPane.ERROR_MESSAGE);
            cmbacceso.requestFocus();
        } else if (proceso.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de modelo", "Atención", JOptionPane.ERROR_MESSAGE);
            cmbTipo.requestFocus();
        } else if (tipo.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un tipo de equipo", "Atención", JOptionPane.ERROR_MESSAGE);
        } else {
            String registro = "---" + codigo + "," + tipo + "," + proceso + "," + acceso
            + "," + fecha() + "," + "Activo" + "," + "2";

            nuevoRegistro(registro, "E:/componentes.in");

            estComponente p = new estComponente();

            p.codigo = codigo;
            p.proceso = proceso;
            p.acceso = acceso;
            p.tipoExp = tipo;
            p.nombre = nombre;

            ultcomp.liga = p;
            ultcomp = p;

            JOptionPane.showMessageDialog(null, "El articulo fue registrado con exito, puede continuar el proceso");
            

            pestanhas(true, true, true);
            camposComponentesOk();
        }
    }//GEN-LAST:event_btnRegiscompActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCambiarCamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarCamActionPerformed
        camposComponentes();
         
        
    }//GEN-LAST:event_btnCambiarCamActionPerformed

    private void btnCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodigoActionPerformed

        String codigo = txtcodigo1.getText();

        estComponente nodoComponente = consultarComponente(codigo);

        if (nodoComponente != null) {
            txtcodigo1.setText(nodoComponente.codigo);
            txtNombre.setText(nodoComponente.nombre);
            cmbPro.setActionCommand(nodoComponente.proceso);
            cmbacceso.setActionCommand(nodoComponente.acceso);
            cmbTipo.setActionCommand(nodoComponente.tipoExp);

            JOptionPane.showMessageDialog(null, "El usuario fue hallado, puede continuar el proceso");
            pestanhas(true, true, true);
            camposComponentesOk();
        } else if (txtcodigo1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el codigo del expediente", "Atención", JOptionPane.ERROR_MESSAGE);
            txtcodigo1.requestFocus();
        } else {
            int option = JOptionPane.showConfirmDialog(rootPane, "El expediente no existe , ¿desea registrarlo?");

            if (option == JOptionPane.NO_OPTION) {
                txtcodigo1.setText("");
            } else if (option == JOptionPane.YES_OPTION) {
                cmbPro.setEditable(true);
                txtNombre.setEditable(true);         
                cmbTipo.setEditable(true);
                cmbacceso.setEditable(true);
                txtcodigo1.setEditable(false);
                btnCodigo.setVisible(true);
                btnCambiarCam.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnCodigoActionPerformed

    private void txtcodigo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigo1KeyTyped

    }//GEN-LAST:event_txtcodigo1KeyTyped

    private void txtcodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigo1ActionPerformed

    private void pnlTituloArtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloArtMouseMoved

    }//GEN-LAST:event_pnlTituloArtMouseMoved

    private void pnlSolicitanteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSolicitanteMouseMoved

    }//GEN-LAST:event_pnlSolicitanteMouseMoved

    private void btnCambiarSoliciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarSoliciActionPerformed
        camposSolicitante();
        pestanhas(true, false, false);
    }//GEN-LAST:event_btnCambiarSoliciActionPerformed

    private void btnRegisSoliciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisSoliciActionPerformed

        String Usuario = txtDocSolicitante.getText();
        String Nombres = txtNombres.getText();
        String Apellidos = txtApellidos.getText();
        String Email = txtEmail.getText();
        //  String Departamento = txtDpto.getText();

        if (Nombres.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de nombres", "Atención", JOptionPane.ERROR_MESSAGE);
            txtNombres.requestFocus();
        } else if (Apellidos.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de apellidos", "Atención", JOptionPane.ERROR_MESSAGE);
            txtApellidos.requestFocus();
        } else if (Email.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo del e-mail", "Atención", JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocus();
        } /*
        * else if (Departamento.equals("")){
            * JOptionPane.showMessageDialog(null, "Falta llenar el campo del
                * departamento", "Atención", JOptionPane.ERROR_MESSAGE);
                * txtDpto.requestFocus();
            }
            */ else {
                String registro = "---" + Usuario + ",," + Nombres + "," + Apellidos
                + "," + Email + "," + "Solicitante" + "," + "Activo" + "," + fecha();

                nuevoRegistro(registro, "E:/usuarios.in");

                estUsuario p = new estUsuario();

                p.usuario = Usuario;
                p.contrasena = "";
                p.nombre = Nombres;
                p.apellido = Apellidos;
                p.email = Email;
                // p.departamento = Departamento;
                p.perfil = "Solicitante";
                p.estado = "Activo";
                p.fecha = fecha();

                ultUsu.liga = p;
                ultUsu = p;

                JOptionPane.showMessageDialog(null, "El usuario fue registrado con exito, puede continuar el proceso");
                pestanhas(true, true, true);

                camposSolicitanteOk();
            }
    }//GEN-LAST:event_btnRegisSoliciActionPerformed

    private void btnCanceRegisSolicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanceRegisSolicActionPerformed
        camposSolicitante();
    }//GEN-LAST:event_btnCanceRegisSolicActionPerformed

    private void btnDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentoActionPerformed

        String codigo = txtDocSolicitante.getText();

        estUsuario nodoUsuario = consultarUsuario(codigo);

        if (nodoUsuario != null) {
            txtNombres.setText(nodoUsuario.nombre);
            txtApellidos.setText(nodoUsuario.apellido);
            txtEmail.setText(nodoUsuario.email);
            // txtDpto.setText(nodoUsuario.departamento);
            txtPerfil.setText(nodoUsuario.perfil);
            txtEstado.setText(nodoUsuario.estado);

            JOptionPane.showMessageDialog(null, "El usuario fue hallado, puede continuar el proceso");
            pestanhas(true, true, false);
            camposSolicitanteOk();
        } else if (txtDocSolicitante.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el documento del solicitante", "Atención", JOptionPane.ERROR_MESSAGE);
            txtDocSolicitante.requestFocus();
        } else {
            int option = JOptionPane.showConfirmDialog(rootPane, "El solicitante no exite, ¿desea registrarlo?");

            if (option == JOptionPane.NO_OPTION) {
                txtDocSolicitante.setText("");
            } else if (option == JOptionPane.YES_OPTION) {
                txtNombres.setEditable(true);
                txtApellidos.setEditable(true);
                txtEmail.setEditable(true);
                // txtDpto.setEditable(true);
                txtPerfil.setText("Solicitante");
                txtEstado.setText("Activo");
                txtDocSolicitante.setEditable(false);
                txtNombres.requestFocus();

                btnRegisSolici.setVisible(true);
                btnCanceRegisSolic.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnDocumentoActionPerformed

    private void txtDocSolicitanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocSolicitanteKeyTyped
        validar.soloNumeros(evt);
    }//GEN-LAST:event_txtDocSolicitanteKeyTyped

    private void pnlTituloMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloMouseMoved

    }//GEN-LAST:event_pnlTituloMouseMoved

    private void cmbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoItemStateChanged

        /*  switch (cmbTipo.getSelectedIndex()) {
            case 2:
            contrasenas(true);
            break;
            case 3:
            contrasenas(true);
            break;
            default:
            contrasenas(false);
            break;
        }*/
    }//GEN-LAST:event_cmbTipoItemStateChanged

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void cmbaccesoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbaccesoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbaccesoItemStateChanged

    private void cmbaccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbaccesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbaccesoActionPerformed

    private void cmbProItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProItemStateChanged

    private void cmbProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProActionPerformed

    private void txtLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugarActionPerformed

    private void txtLugarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarKeyTyped

    }//GEN-LAST:event_txtLugarKeyTyped

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloKeyTyped

    private void txtEstado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstado1ActionPerformed

    private void txtEstado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstado1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstado1KeyTyped

    private void txtFeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        camposAgenda();
        botones(false);
        btnRegistrar.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        String Lugar = txtLugar.getText();
       
        String horaI = txtHoraI.getText();
        String fecha = txtFe.getText();
        String horaF = TxtHT.getText();
        String titulo = txtTitulo.getText();
        String estado = txtEstado.getText();

        if (consultarArticulo(Lugar) != null) {
            JOptionPane.showMessageDialog(null, "la ageda  ya esta registrado", "Atención", JOptionPane.ERROR_MESSAGE);
            txtLugar.requestFocus();
        } else if (Lugar.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de lugar", "Atención", JOptionPane.ERROR_MESSAGE);
            txtLugar.requestFocus();
        } else if (horaF.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de hora final", "Atención", JOptionPane.ERROR_MESSAGE);
            TxtHT.requestFocus();
        } else if (horaI.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de hora de inicio", "Atención", JOptionPane.ERROR_MESSAGE);
            txtHoraI.requestFocus();
        } else if (fecha.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta llenar el campo de fecha", "Atención", JOptionPane.ERROR_MESSAGE);
            txtFe.requestFocus();
        } else {

            String registro = "---" + Lugar + "," + titulo + "," + fecha + "," + horaF + "," + horaI
            +  "Activo"+","+"0"+","+"0";

            nuevoArticulo(registro);

            String miFila[] = {Lugar, fecha, horaF, horaI};
            DefaultTableModel miTabla = (DefaultTableModel) this.tbpSolicitud.getModel();
            miTabla.addRow(miFila);

            JOptionPane.showMessageDialog(null, "La agenda fue registrada con exito");

            btnNuevoActionPerformed(evt);

            estArticulo p = new estArticulo();

            p.lugar = Lugar;
            p.horaF = horaF;
            p.fecha = fecha;
            p.horaI = horaI;
            p.titulo= titulo;
            p.estado= estado;

            ultArt.liga = p;
            ultArt = p;
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        String lugar = txtLugar.getText();
       
        String horaI = txtHoraI.getText();
        String fecha= txtFe.getText();
        String horaF= TxtHT.getText();
        String titulo= txtTitulo.getText();
        String estado = txtEstado.getText();

        if (horaI.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de hora final", "Atención", JOptionPane.ERROR_MESSAGE);
            txtHoraI.requestFocus();
        } else if (horaF.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de hora final", "Atención", JOptionPane.ERROR_MESSAGE);
            TxtHT.requestFocus();
        }else if (fecha.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de fecha", "Atención", JOptionPane.ERROR_MESSAGE);
            txtFe.requestFocus();
        }else {

            btnNuevoActionPerformed(evt);

            String miFila[] = {lugar,fecha, horaI, horaF,titulo,"0"};
            DefaultTableModel miTabla = (DefaultTableModel) this.tbpSolicitud.getModel();           
            miTabla.addRow(miFila);

            estArticulo p = consultarArticulo(lugar);

            p.lugar = lugar;
            p.horaI= horaI;
            p.horaF = horaF;
            p.fecha = fecha;
           
            p.estado= estado;

            modRegistro();
            JOptionPane.showMessageDialog(null, "El artículo fue modificado con exito");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        String Articulo = txtLugar.getText();

        int option = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de que desea cambiar el estado del artículo?");

        if (option == JOptionPane.YES_OPTION) {
            estArticulo p = consultarArticulo(Articulo);
            p.estado= "Inactivo";
            modRegistro();
            txtEstado.setText("Inactivo");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtDocSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocSolicitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocSolicitanteActionPerformed

    public void llenarSolicitud() {
        String codigo = txtDocSolicitante.getText();

        estUsuario nodoUsuario = consultarUsuario(codigo);

        if (nodoUsuario != null) {
            txtNombres.setText(nodoUsuario.nombre);
            txtApellidos.setText(nodoUsuario.apellido);
            txtEmail.setText(nodoUsuario.email);
            // txtDpto.setText(nodoUsuario.departamento);
            txtPerfil.setText(nodoUsuario.perfil);
            txtEstado.setText(nodoUsuario.estado);

            pestanhas(true, true, false);
            camposSolicitanteOk();
        } else if (txtDocSolicitante.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el documento del solicitante", "Atención", JOptionPane.ERROR_MESSAGE);
            txtDocSolicitante.requestFocus();
        } else {
            int option = JOptionPane.showConfirmDialog(rootPane, "El solicitante no exite, ¿desea registrarlo?");

            if (option == JOptionPane.NO_OPTION) {
                txtDocSolicitante.setText("");
            } else if (option == JOptionPane.YES_OPTION) {
                txtNombres.setEditable(true);
                txtApellidos.setEditable(true);
                txtEmail.setEditable(true);
                // txtDpto.setEditable(true);
                txtPerfil.setText("Solicitante");
                txtEstado.setText("Activo");
                txtDocSolicitante.setEditable(false);
                txtNombres.requestFocus();

                btnRegisSolici.setVisible(true);
                btnCanceRegisSolic.setVisible(true);
            }
        }
    }
public void llenarComponente() {
        String codigo = txtcodigo1.getText();

        estComponente nodoComponente = consultarComponente(codigo);

        if (nodoComponente != null) {
            txtNombre.setText(nodoComponente.nombre);
            txtcodigo1.setText(nodoComponente.codigo);
            cmbacceso.setActionCommand(nodoComponente.acceso);
            // txtDpto.setText(nodoUsuario.departamento);
            cmbPro.setActionCommand(nodoComponente.proceso);
            cmbacceso.setActionCommand(nodoComponente.tipoExp);

            pestanhas(true, true, false);
            camposComponentesOk();
        } else if (txtcodigo1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el documento del solicitante", "Atención", JOptionPane.ERROR_MESSAGE);
            txtcodigo1.requestFocus();
        } else {
            int option = JOptionPane.showConfirmDialog(rootPane, "El solicitante no exite, ¿desea registrarlo?");

            if (option == JOptionPane.NO_OPTION) {
                txtcodigo1.setText("");
            } else if (option == JOptionPane.YES_OPTION) {
                txtNombres.setEditable(true);
                cmbPro.setEditable(true);
                cmbTipo.setEditable(true);
                // txtDpto.setEditable(true);
                cmbacceso.setEditable(true);
                txtcodigo1.setEditable(false);
                txtcodigo1.requestFocus();

                btnCodigo.setVisible(true);
                btnCambiarCam.setVisible(true);
            }
        }
}
    //Procedimiento para dar colores al formulario
    private void formColores(String color1, String color2, String color3) {
        this.getContentPane().setBackground(new Color(Integer.parseInt(color2, 16)));
        pnlSolicitante.setBackground(new Color(Integer.parseInt(color1, 16)));
        tbpSolicitud.setBackground(new Color(Integer.parseInt(color1, 16)));

        pnlTitulo.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTitulo.setForeground(new Color(Integer.parseInt(color3, 16)));

        pnlArticulo.setBackground(new Color(Integer.parseInt(color1, 16)));

        pnlTituloArt.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTituloArt.setForeground(new Color(Integer.parseInt(color3, 16)));

        pnlSolicitud.setBackground(new Color(Integer.parseInt(color1, 16)));

        pnlTituloSoli.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTituloSoli.setForeground(new Color(Integer.parseInt(color3, 16)));
    }

    //Procedimiento para llenar la tabla de chequeo
   

    private void camposSolicitante() {

        txtNombres.setEditable(false);
        txtApellidos.setEditable(false);
        txtEmail.setEditable(false);
        //txtDpto.setEditable(false);
        txtPerfil.setEditable(false);
        txtEstado.setEditable(false);
        txtDocSolicitante.setEditable(true);

        btnRegisSolici.setVisible(false);
        btnCanceRegisSolic.setVisible(false);

        txtDocSolicitante.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtEmail.setText("");
        //txtDpto.setText("");
        txtPerfil.setText("");
        txtEstado.setText("");

    }

    private void camposSolicitanteOk() {

        txtNombres.setEditable(false);
        txtApellidos.setEditable(false);
        txtEmail.setEditable(false);
        // txtDpto.setEditable(false);
        txtPerfil.setEditable(false);
        txtEstado.setEditable(false);
        txtDocSolicitante.setEditable(false);

        btnRegisSolici.setVisible(false);
        btnCanceRegisSolic.setVisible(false);

    }

    private void camposComponentes() {
       txtNombre.setEditable(false);
        cmbPro.setEditable(false);
        txtcodigo1.setEditable(true);
        cmbTipo.setEditable(false);
        cmbacceso.setEditable(false);
        btnRegiscomp.setVisible(false);
        btnCanceRegisComp.setVisible(false);
        txtcodigo1.setText("");
        txtcodigo1.setText("");
        cmbPro.setActionCommand("");
        cmbTipo.setActionCommand("");
        txtNombre.setText("");
        cmbacceso.setActionCommand("");

        btnRegiscomp.setVisible(false);
        btnCanceRegisComp.setVisible(false);

    }

    private void camposComponentesOk() {

        txtNombre.setEditable(false);
        cmbPro.setEditable(false);
        txtcodigo1.setEditable(false);
        cmbTipo.setEditable(false);
        cmbacceso.setEditable(false);
        btnRegiscomp.setVisible(false);
        btnCanceRegisComp.setVisible(false);
        
        btnRegiscomp.setVisible(true);
        btnCanceRegisComp.setVisible(true);
        
    }
     private void camposAgenda() {
        
        txtFe.setText("");
        txtHoraI.setText("");
        txtLugar.setText("");
        txtTitulo.setText("");
        TxtHT.setText("");
        txtFe.setText("");

        btnRegiscomp.setVisible(false);
        btnCanceRegisComp.setVisible(false);

    }

    private void camposAgendaOk() {

        txtNombre.setEditable(false);
        cmbPro.setEditable(false);
        txtcodigo1.setEditable(false);
        cmbTipo.setEditable(false);
        cmbacceso.setEditable(false);
        btnRegiscomp.setVisible(false);
        btnCanceRegisComp.setVisible(false);
        
        btnRegiscomp.setVisible(true);
        btnCanceRegisComp.setVisible(true);
        
    }
       public void botones(boolean a) {

        btnModificar.setEnabled(a);
        btnEliminar.setEnabled(a);
    }

    private void pestanhas(boolean x, boolean y, boolean z) {
        tbpSolicitud.setEnabledAt(0, x);
        tbpSolicitud.setEnabledAt(1, y);
        tbpSolicitud.setEnabledAt(2, z);
    }
    
    

    private String fecha() {
        Calendar Calendario = Calendar.getInstance();

        String anho = Integer.toString(Calendario.get(Calendar.YEAR));
        String mes = Integer.toString(Calendario.get(Calendar.MONTH) + 1);
        String dia = Integer.toString(Calendario.get(Calendar.DATE));

        return (dia + "/" + mes + "/" + anho);
    }

    private estUsuario consultarUsuario(String usuario) {
        estUsuario p = cabUsu;

        while (p != null) {
            if (p.usuario.equals(usuario)) {
                return p;
            }
            p = p.liga;
        }
        return null;
    }

    private estArticulo consultarArticulo(String articulo) {
        estArticulo p = cabArt;

        while (p != null) {
            if (p.titulo.equals(articulo)) {
                return p;
            }
            p = p.liga;
        }
        return null;
    }

    public estComponente consultarComponente(String componente) {
        estComponente p = cabcomp;
        String d="no entro";
        while (p != null) {
            d=p.codigo;
            if (p.codigo.equals(componente)) {
                
                return p;
            }
            p = p.liga;
        }
        return null;
    }

    private void nuevoRegistro(String registro, String path) {
        File f;
        f = new File(path);
        try {
            FileWriter fw = new FileWriter(f, true);
            fw.append(registro);
            fw.close();
        } catch (IOException e) {
        };
    }

    private void cargarUsuarios() {
        try {
            File f = new File("E:/usuarios.in");
            BufferedReader entrada;
            entrada = new BufferedReader(new FileReader(f));
            String[] nodos = entrada.readLine().split("---"), valores;

            estUsuario p;

            for (int i = 0; i < nodos.length; i++) {
                p = new estUsuario();

                if (p == null) {
                    System.out.println("Memoria llena");
                } else {
                    valores = nodos[i].split(",");

                    p.usuario = valores[0];
                    p.contrasena = valores[1];
                    p.nombre = valores[2];
                    p.apellido = valores[3];
                    p.email = valores[4];
                    //  p.departamento = valores[5];
                    p.perfil = valores[5];
                    p.estado = valores[6];
                    p.fecha = valores[7];

                    if (cabUsu == null) {
                        cabUsu = p;
                    } else {
                        ultUsu.liga = p;
                    }
                    ultUsu = p;
                }
            }

            p = cabUsu;

         

        } catch (IOException e) {
            System.out.println("Error: " + e);
        }
    }

    private void cargarArticulos() {
        try {
            File f = new File("E:/articulos.in");
            BufferedReader entrada;
            entrada = new BufferedReader(new FileReader(f));
            String[] nodos = entrada.readLine().split("---"), valores;

            estArticulo p;

            for (int i = 0; i < nodos.length; i++) {
                p = new estArticulo();

                if (p == null) {
                    System.out.println("Memoria llena");
                } else {
                    valores = nodos[i].split(",");

                    p.lugar = valores[0];
                    p.horaF= valores[1];
                    p.horaI = valores[2];
                    p.fecha= valores[3];
                    p.titulo = valores[4];
                    p.descripcion= valores[5];
                    p.estado = valores[6];

                    if (cabArt == null) {
                        cabArt = p;
                    } else {
                        ultArt.liga = p;
                    }
                    ultArt = p;
                }
            }
        } catch (IOException e) {
            System.out.println("Error: " + e);
        }
    }

    private void cargarComponente() {
        try {
            File f = new File("E:/componentes.in");
            BufferedReader entrada;
            entrada = new BufferedReader(new FileReader(f));
            String[] nodos = entrada.readLine().split("---"), valores;

            estComponente p;

            for (int i = 0; i < nodos.length; i++) {
                p = new estComponente();

                if (p == null) {
                    System.out.println("Memoria llena");
                } else {
                    valores = nodos[i].split(",");

                     p.codigo = valores[0];
                     p.nombre = valores[1];
                    p.proceso = valores[2];
                    p.tipoExp = valores[3];
                    p.descripcion = valores[4];
                    p.acceso = valores[5];

                    if (cabcomp == null) {
                        cabcomp = p;
                    } else {
                        ultcomp.liga = p;
                    }
                    ultcomp = p;
                }
            }
        } catch (IOException e) {
            System.out.println("Error: " + e);
        }
    }
        private void nuevoArticulo(String registro) {
        File f;
        f = new File("E:/articulos.in");
        try {
            FileWriter fw = new FileWriter(f, true);
            fw.append(registro);
            fw.close();
        } catch (IOException e) {
        };
    }

        private void modRegistro() 
    {
        estArticulo p = cabArt;
        String registro = "---";
        
        File f = new File("E:/articulos.in");
        
        try {
            Writer output = new BufferedWriter(new FileWriter(f));
            try {
                output.write("");
            }
            finally {
                output.close();
            }
        }
        catch (IOException e){}
        
        if (p == null) {
            System.out.println("Lista vacia");
        } 
        else {
            while (p != null) {
                
                if (p == cabArt){
                    registro = "";
                }
                
                registro += p.lugar + "," +p.titulo+","+ p.fecha + "," + p.horaI + "," + p.horaF
                        + "," + p.descripcion+ "," + "Activo" ;
                
                nuevoArticulo(registro);
                registro = "---";
                p = p.liga;
            }
        }
    }
    private void cargarDatos() {
        try {
            File f = new File("E:/reparaciones.in");
            BufferedReader entrada;
            entrada = new BufferedReader(new FileReader(f));
            String[] nodos = entrada.readLine().split("---"), valores;

            estReparacion p;
            estComponente r;
            estUsuario w; 

            for (int i = 0; i < nodos.length; i++) {
                p = new estReparacion();

                if (p == null) {
                    System.out.println("Memoria llena");
                } else {
                    valores = nodos[i].split(",");

                    p.usuario = valores[0];
                    p.apellido= valores[1];
                    p. DocSolicitante= valores[2];
                    p.codigoE = valores[3];
                    p.lugarE= valores[4];
                    p.codigoA = valores[5];
                    p.hora = valores[6];
                    p.fecha = valores[7];

                    if (cab == null) {
                        cab = p;
                    } else {
                        ult.liga = p;
                    }
                    ult = p;
                }
            }
        } catch (IOException e) {
            System.out.println("Error: " + e);
        }
    }

    public String numReparaciones() {
        estReparacion p = cab;
        int i = 0;

        while (p != null) {
            i++;
            p = p.liga;
        }

        return i + "";
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtHT;
    private javax.swing.JButton btnCambiarCam;
    private javax.swing.JButton btnCambiarSolici;
    private javax.swing.JButton btnCanceRegisComp;
    private javax.swing.JButton btnCanceRegisSolic;
    private javax.swing.JButton btnCodigo;
    private javax.swing.JButton btnDocumento;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegisSolici;
    private javax.swing.JButton btnRegiscomp;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox cmbPro;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JComboBox cmbacceso;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbDocSolicitante;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbEstado1;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbModelo;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbNumSerie;
    private javax.swing.JLabel lbNumSerie1;
    private javax.swing.JLabel lbNumSerie2;
    private javax.swing.JLabel lbPerfil;
    private javax.swing.JLabel lbTipo1;
    private javax.swing.JLabel lbTipo2;
    private javax.swing.JLabel lbTipo3;
    private javax.swing.JLabel lbTipo4;
    private javax.swing.JLabel lbTipo5;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTituloArt;
    private javax.swing.JLabel lbTituloSoli;
    private javax.swing.JPanel pnlArticulo;
    private javax.swing.JPanel pnlBotonesSolicitante;
    private javax.swing.JPanel pnlBotonesSolicitante1;
    private javax.swing.JPanel pnlSolicitante;
    private javax.swing.JPanel pnlSolicitud;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlTituloArt;
    private javax.swing.JPanel pnlTituloSoli;
    private javax.swing.JSeparator separaArt;
    private javax.swing.JSeparator separaSolici;
    private javax.swing.JTabbedPane tbpSolicitud;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDocSolicitante;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEstado1;
    private javax.swing.JTextField txtFe;
    private javax.swing.JTextField txtHoraI;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPerfil;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtcodigo1;
    // End of variables declaration//GEN-END:variables
}
