package formularios;

import clases.SQL;
import clases.listas.estArticulo;
import clases.listas.estReparacion;
import java.awt.Color;
import java.io.*;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class IfrmCrudEntrega extends javax.swing.JInternalFrame {

    SQL sql = new SQL();
    usuarioLogueado usuarioLogin = new usuarioLogueado();
    validacionesCampos validar = new validacionesCampos();
    static estReparacion cab = null, ult = null;
    
    public IfrmCrudEntrega() {
        initComponents();
        
        
        /*String usu[] = sql.consultarUsuario(usuarioLogin.texto);
        
        if (!usu[4].equals("Administrador")){
            jButton1.setVisible(false);
            tbpCrudComponentes.remove(1);
        }*/
        
        cargarDatos();
        formColores("FFFFFF", "6699ff", "FFFFFF"); 
        tbpCrudComponentes.setTabPlacement(tbpCrudComponentes.BOTTOM);
         
        
        txtFiltrador.requestFocus();
        llenarTabla();
        //botones(false);
        camposArticulos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpCrudComponentes = new javax.swing.JTabbedPane();
        pnlTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComponentes = new javax.swing.JTable();
        pnlTituloTabla = new javax.swing.JPanel();
        lbTituloTabla = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtFiltrador = new javax.swing.JTextField();
        pnlFormulario = new javax.swing.JPanel();
        pnlTituloCom = new javax.swing.JPanel();
        lbTituloArt = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lbTipo = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        lbUbicacion = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        pnlBotonesArticulo = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        lbDescripcion = new javax.swing.JLabel();
        lbCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextPane();

        tbpCrudComponentes.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        tbpCrudComponentes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tbpCrudComponentesMouseMoved(evt);
            }
        });

        pnlTabla.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTablaMouseMoved(evt);
            }
        });

        tblComponentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Tipo", "Ubicacion", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblComponentes.setName("");
        jScrollPane1.setViewportView(tblComponentes);

        pnlTituloTabla.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloTablaMouseMoved(evt);
            }
        });

        lbTituloTabla.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        lbTituloTabla.setText(" Entrega");

        javax.swing.GroupLayout pnlTituloTablaLayout = new javax.swing.GroupLayout(pnlTituloTabla);
        pnlTituloTabla.setLayout(pnlTituloTablaLayout);
        pnlTituloTablaLayout.setHorizontalGroup(
            pnlTituloTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloTablaLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(lbTituloTabla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloTablaLayout.setVerticalGroup(
            pnlTituloTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton1.setText("Transferir al formulario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtFiltrador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltradorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(pnlTituloTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(txtFiltrador, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap())
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaLayout.createSequentialGroup()
                .addComponent(pnlTituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        tbpCrudComponentes.addTab("Tabla", pnlTabla);

        pnlFormulario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlFormularioMouseMoved(evt);
            }
        });

        pnlTituloCom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloComMouseMoved(evt);
            }
        });

        lbTituloArt.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        lbTituloArt.setText("Componentes");

        javax.swing.GroupLayout pnlTituloComLayout = new javax.swing.GroupLayout(pnlTituloCom);
        pnlTituloCom.setLayout(pnlTituloComLayout);
        pnlTituloComLayout.setHorizontalGroup(
            pnlTituloComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloComLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(lbTituloArt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloComLayout.setVerticalGroup(
            pnlTituloComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloComLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloArt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbCodigo.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbCodigo.setText("*Código");

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        lbTipo.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbTipo.setText("*Tipo");

        lbNombre.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbNombre.setText("*Nombre");

        lbUbicacion.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbUbicacion.setText("*Ubicación");

        pnlBotonesArticulo.setBackground(new java.awt.Color(255, 255, 255));

        btnModificar.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesArticuloLayout = new javax.swing.GroupLayout(pnlBotonesArticulo);
        pnlBotonesArticulo.setLayout(pnlBotonesArticuloLayout);
        pnlBotonesArticuloLayout.setHorizontalGroup(
            pnlBotonesArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesArticuloLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(btnModificar)
                .addGap(120, 120, 120))
        );
        pnlBotonesArticuloLayout.setVerticalGroup(
            pnlBotonesArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesArticuloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnModificar))
        );

        lbDescripcion.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbDescripcion.setText("Descripción");

        lbCantidad.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbCantidad.setText("*Cantidad");

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jScrollPane2.setViewportView(txtDescripcion);

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                        .addComponent(pnlBotonesArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                                    .addComponent(lbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(pnlFormularioLayout.createSequentialGroup()
                                    .addComponent(lbNombre)
                                    .addGap(10, 10, 10)))
                            .addGroup(pnlFormularioLayout.createSequentialGroup()
                                .addComponent(lbTipo)
                                .addGap(32, 32, 32)))
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtNombre)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlFormularioLayout.createSequentialGroup()
                                .addComponent(lbCantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCantidad))
                            .addGroup(pnlFormularioLayout.createSequentialGroup()
                                .addComponent(lbUbicacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                .addGap(0, 68, Short.MAX_VALUE)
                .addComponent(lbDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addComponent(pnlTituloCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCodigo))
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormularioLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlFormularioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(pnlBotonesArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        tbpCrudComponentes.addTab("Formulario", pnlFormulario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpCrudComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpCrudComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbpCrudComponentesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpCrudComponentesMouseMoved

   }//GEN-LAST:event_tbpCrudComponentesMouseMoved

    private void pnlFormularioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFormularioMouseMoved

   }//GEN-LAST:event_pnlFormularioMouseMoved

    private void pnlTituloComMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloComMouseMoved

   }//GEN-LAST:event_pnlTituloComMouseMoved

    private void pnlTablaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTablaMouseMoved

   }//GEN-LAST:event_pnlTablaMouseMoved

    private void txtFiltradorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltradorKeyReleased

        DefaultTableModel modelo = (DefaultTableModel) tblComponentes.getModel();
        TableRowSorter sorter = new TableRowSorter(modelo);
        tblComponentes.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)^" + txtFiltrador.getText(), 0));
    }//GEN-LAST:event_txtFiltradorKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
           
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pnlTituloTablaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloTablaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloTablaMouseMoved

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        String usuario = txtCodigo.getText();
        String nombre = txtNombre.getText();
        String tipo = txtTipo.getText();
        String ubicacion = txtUbicacion.getText();
        String cantidad = txtCantidad.getText();
        String descripcion = txtDescripcion.getText();

        if (nombre.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de nombre", "Atención", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
        } else if (tipo.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de tipo", "Atención", JOptionPane.ERROR_MESSAGE);
            txtTipo.requestFocus();
        } else if (ubicacion.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar dar la ubicación", "Atención", JOptionPane.ERROR_MESSAGE);
            txtUbicacion.requestFocus();
        } else if (cantidad.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de cantidad", "Atención", JOptionPane.ERROR_MESSAGE);
            txtCantidad.requestFocus();
        } else {

            

            String miFila[] = {usuario, nombre, tipo, ubicacion, cantidad};

            DefaultTableModel miTabla = (DefaultTableModel) this.tblComponentes.getModel();
            miTabla.removeRow(tblComponentes.getSelectedRow());
            miTabla.addRow(miFila);

            estReparacion p = consultarComponente(usuario);

            p.usuario = usuario;
            p. tecnico= tipo;
            p.fecha = ubicacion;
            p.estado = descripcion;
            p.comentarios = cantidad;

            
            JOptionPane.showMessageDialog(null, "El componente fue modificado con exito");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        validar.soloNumeros(evt);
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        validar.soloNumeros(evt);
    }//GEN-LAST:event_txtCodigoKeyTyped

            //Procedimiento para dar colores al formulario
    private void formColores (String color1, String color2, String color3) 
    {
        this.getContentPane().setBackground(new Color(Integer.parseInt(color2, 16)));
        pnlFormulario.setBackground(new Color(Integer.parseInt(color1, 16)));
        pnlTabla.setBackground(new Color(Integer.parseInt(color1, 16)));
        tbpCrudComponentes.setBackground(new Color(Integer.parseInt(color1, 16)));
        
        pnlTituloCom.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTituloArt.setForeground(new Color(Integer.parseInt(color3, 16)));
        
        pnlTituloTabla.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTituloTabla.setForeground(new Color(Integer.parseInt(color3, 16)));
    }   
    
    private void llenarTabla ()
    {  
        DefaultTableModel miModelo = (DefaultTableModel)this.tblComponentes.getModel();
        
        ArrayList<Object[]> data = new ArrayList<>();
        
        estReparacion p = cab;
        
        while (p != null) {
            String[] datos = {p.usuario, p.tecnico, p.fecha, p.estado, p.comentarios,p.chequeo,p.articulo,p.adminIng};
            data.add(datos);
            p = p.liga;
        }

        for (int i = 0; i < data.size(); i++) {
            miModelo.addRow(data.get(i));
        }
        
        tblComponentes.setRowHeight(25);
    }
    
   
    
    private void camposArticulos () {
        txtCodigo.setText("");
        txtCantidad.setText("0");
        txtTipo.setText("");
        txtUbicacion.setText("");
        txtNombre.setText("");
        txtDescripcion.setText(null);

        txtCodigo.setEditable(true);
    }
        
    
    private void cargarDatos() {
        try {
            File f = new File("E:/componentes.in");
            BufferedReader entrada;
            entrada = new BufferedReader(new FileReader(f));
            String[] nodos = entrada.readLine().split("---"), valores;

            estReparacion p;

            for (int i = 0; i < nodos.length; i++) {
                p = new estReparacion();

                if (p == null) {
                    System.out.println("Memoria llena");
                } else {
                    valores = nodos[i].split(",");

                    p.usuario = valores[0];
                    p.tecnico = valores[1];
                    p.fecha = valores[2];
                    p.estado = valores[3];
                    p.comentarios = valores[4];
                    p.chequeo = valores[5];
                    p.articulo= valores[6];
                    p.adminIng= valores[7];
                    
                    if (cab == null) {
                        cab = p;
                    } else {
                        ult.liga = p;
                    }
                    ult = p;
                }
            }
        } catch (IOException e) {
            System.out.println("Error: " + e);
        }
    }
    
    private estReparacion consultarComponente(String componente) {
        estReparacion p = cab;

        while (p != null) {
            if (p.usuario.equals(componente)) {
                return p;
            }
            p = p.liga;
        }
        return null;
    }

    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTituloArt;
    private javax.swing.JLabel lbTituloTabla;
    private javax.swing.JLabel lbUbicacion;
    private javax.swing.JPanel pnlBotonesArticulo;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JPanel pnlTituloCom;
    private javax.swing.JPanel pnlTituloTabla;
    private javax.swing.JTable tblComponentes;
    private javax.swing.JTabbedPane tbpCrudComponentes;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextPane txtDescripcion;
    private javax.swing.JTextField txtFiltrador;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
