/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import jctablecheckdel.Celda_CheckBox;
import jctablecheckdel.Render_CheckBox;
import clases.SQL;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Cristian Morales
 */
public class IfrmFinalizacion extends javax.swing.JInternalFrame {

   SQL sql = new SQL();
   static int codigo;
   usuarioLogueado usuarioLogin = new usuarioLogueado();
   validacionesCampos validar = new validacionesCampos();
    
    public IfrmFinalizacion() {
        
        initComponents();
        formColores("FFFFFF", "6699ff", "FFFFFF"); 
        tbpSolicitud.setTabPlacement(tbpSolicitud.BOTTOM);
        
        camposArticulos();
        llenarSolicitudes();
        llenarTabla();
        
        btnDocumento.setVisible(false);
        btnNumSerie.setVisible(false);

        grupoTipo.add(rbPortatil);
        grupoTipo.add(rdComputador);
        grupoTipo.add(rdImpresora);
        
        rbPortatil.setEnabled(false);
        rdComputador.setEnabled(false);
        rdImpresora.setEnabled(false);
 
        lbId.setVisible(false);
        mnEliminar.setText("Eliminar");
        
        pestanhas(true, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        ppmTabla = new javax.swing.JPopupMenu();
        mnEliminar = new javax.swing.JMenuItem();
        tbpSolicitud = new javax.swing.JTabbedPane();
        pnlSolicitante = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSolicitudes = new javax.swing.JTable();
        pnlTituloSolicitudes = new javax.swing.JPanel();
        lbTituloSolicitudes = new javax.swing.JLabel();
        btnDocumento1 = new javax.swing.JButton();
        pnlArticulo = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbDocSolicitante = new javax.swing.JLabel();
        txtDocSolicitante = new javax.swing.JTextField();
        lbNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        lbApellidos = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtDpto = new javax.swing.JTextField();
        lbDpto = new javax.swing.JLabel();
        btnDocumento = new javax.swing.JButton();
        pnlSolicitud = new javax.swing.JPanel();
        pnlTituloArt = new javax.swing.JPanel();
        lbTituloArt = new javax.swing.JLabel();
        lbNumSerie = new javax.swing.JLabel();
        txtNumSerie = new javax.swing.JTextField();
        lbTipo = new javax.swing.JLabel();
        lbMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lbModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lbPortatil = new javax.swing.JLabel();
        rbPortatil = new javax.swing.JRadioButton();
        rdComputador = new javax.swing.JRadioButton();
        lbComputador = new javax.swing.JLabel();
        rdImpresora = new javax.swing.JRadioButton();
        lbImpresora = new javax.swing.JLabel();
        btnNumSerie = new javax.swing.JButton();
        pnlFallos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChequeo = new javax.swing.JTable();
        pnlTituloFallos = new javax.swing.JPanel();
        lbTituloFallos = new javax.swing.JLabel();
        lbComentarios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JEditorPane();
        pnlComponentes = new javax.swing.JPanel();
        pnlTituloCompo = new javax.swing.JPanel();
        lbTituloCompo = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblComponentes = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblCompoAnha = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtFiltrador = new javax.swing.JTextField();
        lbCantida = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        pnlFinalizacion = new javax.swing.JPanel();
        pnlTituloFinal = new javax.swing.JPanel();
        lbTituloFinal = new javax.swing.JLabel();
        lbReporte = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtReporte = new javax.swing.JEditorPane();
        lbEstadoFinal = new javax.swing.JLabel();
        cmbFinal = new javax.swing.JComboBox();
        btnFinalizar = new javax.swing.JButton();

        mnEliminar.setText("jMenuItem1");
        mnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEliminarActionPerformed(evt);
            }
        });
        ppmTabla.add(mnEliminar);

        tbpSolicitud.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        tbpSolicitud.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tbpSolicitudMouseMoved(evt);
            }
        });

        pnlSolicitante.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlSolicitanteMouseMoved(evt);
            }
        });

        tblSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Articulo", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblSolicitudes);

        pnlTituloSolicitudes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloSolicitudesMouseMoved(evt);
            }
        });

        lbTituloSolicitudes.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        lbTituloSolicitudes.setText("Solicitudes");

        javax.swing.GroupLayout pnlTituloSolicitudesLayout = new javax.swing.GroupLayout(pnlTituloSolicitudes);
        pnlTituloSolicitudes.setLayout(pnlTituloSolicitudesLayout);
        pnlTituloSolicitudesLayout.setHorizontalGroup(
            pnlTituloSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSolicitudesLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(lbTituloSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloSolicitudesLayout.setVerticalGroup(
            pnlTituloSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSolicitudesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDocumento1.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnDocumento1.setText("Transferir");
        btnDocumento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumento1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSolicitanteLayout = new javax.swing.GroupLayout(pnlSolicitante);
        pnlSolicitante.setLayout(pnlSolicitanteLayout);
        pnlSolicitanteLayout.setHorizontalGroup(
            pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloSolicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitanteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDocumento1)
                .addGap(19, 19, 19))
        );
        pnlSolicitanteLayout.setVerticalGroup(
            pnlSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitanteLayout.createSequentialGroup()
                .addComponent(pnlTituloSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDocumento1)
                .addContainerGap())
        );

        tbpSolicitud.addTab("Solicitudes", pnlSolicitante);

        pnlArticulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlArticuloMouseMoved(evt);
            }
        });

        pnlTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloMouseMoved(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        lbTitulo.setText("Solicitante");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbDocSolicitante.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbDocSolicitante.setText("Documento");

        txtDocSolicitante.setEditable(false);

        lbNombres.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbNombres.setText("Nombres");

        txtNombres.setEditable(false);

        txtApellidos.setEditable(false);

        lbApellidos.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbApellidos.setText("Apellidos");

        txtEmail.setEditable(false);

        lbEmail.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbEmail.setText("E-mail");

        txtDpto.setEditable(false);

        lbDpto.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbDpto.setText("Departamento");

        btnDocumento.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnDocumento.setText("Aceptar");
        btnDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlArticuloLayout = new javax.swing.GroupLayout(pnlArticulo);
        pnlArticulo.setLayout(pnlArticuloLayout);
        pnlArticuloLayout.setHorizontalGroup(
            pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArticuloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDocumento)
                .addGap(25, 25, 25))
            .addGroup(pnlArticuloLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                        .addComponent(lbDpto)
                        .addGap(18, 18, 18)
                        .addComponent(txtDpto))
                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                        .addComponent(lbNombres)
                        .addGap(8, 8, 8)
                        .addComponent(txtNombres))
                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                        .addComponent(lbDocSolicitante)
                        .addGap(18, 18, 18)
                        .addComponent(txtDocSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbApellidos)
                            .addComponent(lbEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlArticuloLayout.setVerticalGroup(
            pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArticuloLayout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDocSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDpto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDpto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnDocumento)
                .addContainerGap())
        );

        tbpSolicitud.addTab("Solicitante", pnlArticulo);

        pnlTituloArt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloArtMouseMoved(evt);
            }
        });

        lbTituloArt.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        lbTituloArt.setText("Articulo");

        javax.swing.GroupLayout pnlTituloArtLayout = new javax.swing.GroupLayout(pnlTituloArt);
        pnlTituloArt.setLayout(pnlTituloArtLayout);
        pnlTituloArtLayout.setHorizontalGroup(
            pnlTituloArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloArtLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(lbTituloArt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloArtLayout.setVerticalGroup(
            pnlTituloArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloArtLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloArt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbNumSerie.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbNumSerie.setText("Numero de serie");

        txtNumSerie.setEditable(false);

        lbTipo.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbTipo.setText("Tipo");

        lbMarca.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbMarca.setText("Marca");

        txtMarca.setEditable(false);

        lbModelo.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbModelo.setText("Modelo");

        txtModelo.setEditable(false);

        rbPortatil.setText("Portatil");
        rbPortatil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbPortatilMouseClicked(evt);
            }
        });
        rbPortatil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPortatilActionPerformed(evt);
            }
        });

        rdComputador.setText("Computador");
        rdComputador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdComputadorActionPerformed(evt);
            }
        });

        rdImpresora.setText("Impresora");
        rdImpresora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdImpresoraMouseClicked(evt);
            }
        });
        rdImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdImpresoraActionPerformed(evt);
            }
        });

        btnNumSerie.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnNumSerie.setText("Aceptar");
        btnNumSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumSerieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSolicitudLayout = new javax.swing.GroupLayout(pnlSolicitud);
        pnlSolicitud.setLayout(pnlSolicitudLayout);
        pnlSolicitudLayout.setHorizontalGroup(
            pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlSolicitudLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSolicitudLayout.createSequentialGroup()
                        .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSolicitudLayout.createSequentialGroup()
                                .addComponent(lbNumSerie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlSolicitudLayout.createSequentialGroup()
                                .addComponent(lbTipo)
                                .addGap(18, 18, 18)
                                .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbPortatil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlSolicitudLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(lbComputador, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlSolicitudLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdComputador)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdImpresora)
                                    .addComponent(lbImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSolicitudLayout.createSequentialGroup()
                        .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSolicitudLayout.createSequentialGroup()
                                .addComponent(lbModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtModelo))
                            .addGroup(pnlSolicitudLayout.createSequentialGroup()
                                .addComponent(lbMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(108, 108, 108)
                        .addComponent(btnNumSerie)
                        .addGap(51, 51, 51))))
        );
        pnlSolicitudLayout.setVerticalGroup(
            pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolicitudLayout.createSequentialGroup()
                .addComponent(pnlTituloArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNumSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPortatil)
                    .addComponent(rdComputador)
                    .addComponent(rdImpresora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbComputador, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNumSerie))
                    .addComponent(lbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        tbpSolicitud.addTab("Articulo", pnlSolicitud);

        tblChequeo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tblChequeo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fallo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblChequeo);

        pnlTituloFallos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloFallosMouseMoved(evt);
            }
        });

        lbTituloFallos.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        lbTituloFallos.setText("Fallos");

        javax.swing.GroupLayout pnlTituloFallosLayout = new javax.swing.GroupLayout(pnlTituloFallos);
        pnlTituloFallos.setLayout(pnlTituloFallosLayout);
        pnlTituloFallosLayout.setHorizontalGroup(
            pnlTituloFallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloFallosLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(lbTituloFallos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloFallosLayout.setVerticalGroup(
            pnlTituloFallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloFallosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloFallos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbComentarios.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbComentarios.setText("Comentarios:");

        txtComentarios.setEditable(false);
        jScrollPane2.setViewportView(txtComentarios);

        javax.swing.GroupLayout pnlFallosLayout = new javax.swing.GroupLayout(pnlFallos);
        pnlFallos.setLayout(pnlFallosLayout);
        pnlFallosLayout.setHorizontalGroup(
            pnlFallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloFallos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFallosLayout.createSequentialGroup()
                .addGroup(pnlFallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFallosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbComentarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(pnlFallosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        pnlFallosLayout.setVerticalGroup(
            pnlFallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFallosLayout.createSequentialGroup()
                .addComponent(pnlTituloFallos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGroup(pnlFallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFallosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFallosLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbComentarios)))
                .addContainerGap())
        );

        tbpSolicitud.addTab("Fallos", pnlFallos);

        pnlTituloCompo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloCompoMouseMoved(evt);
            }
        });

        lbTituloCompo.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        lbTituloCompo.setText("Componentes");

        javax.swing.GroupLayout pnlTituloCompoLayout = new javax.swing.GroupLayout(pnlTituloCompo);
        pnlTituloCompo.setLayout(pnlTituloCompoLayout);
        pnlTituloCompoLayout.setHorizontalGroup(
            pnlTituloCompoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloCompoLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(lbTituloCompo)
                .addGap(55, 55, 55)
                .addComponent(lbId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloCompoLayout.setVerticalGroup(
            pnlTituloCompoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloCompoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloCompoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTituloCompoLayout.createSequentialGroup()
                        .addComponent(lbTituloCompo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloCompoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbId)
                        .addGap(46, 46, 46))))
        );

        tblComponentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Tipo", "Ubicacion", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblComponentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComponentesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblComponentesMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tblComponentes);

        tblCompoAnha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Tipo", "Ubicacion", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCompoAnha.setComponentPopupMenu(ppmTabla);
        jScrollPane5.setViewportView(tblCompoAnha);

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtFiltrador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltradorKeyReleased(evt);
            }
        });

        lbCantida.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        lbCantida.setText("Cantidad utilizada");

        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCantidadFocusGained(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlComponentesLayout = new javax.swing.GroupLayout(pnlComponentes);
        pnlComponentes.setLayout(pnlComponentesLayout);
        pnlComponentesLayout.setHorizontalGroup(
            pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloCompo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addGroup(pnlComponentesLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltrador, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbCantida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad)
                        .addGap(26, 26, 26)))
                .addContainerGap())
        );
        pnlComponentesLayout.setVerticalGroup(
            pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComponentesLayout.createSequentialGroup()
                .addComponent(pnlTituloCompo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtFiltrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCantida)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbpSolicitud.addTab("Componentes", pnlComponentes);

        pnlTituloFinal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloFinalMouseMoved(evt);
            }
        });

        lbTituloFinal.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        lbTituloFinal.setText("Finalizacion");

        javax.swing.GroupLayout pnlTituloFinalLayout = new javax.swing.GroupLayout(pnlTituloFinal);
        pnlTituloFinal.setLayout(pnlTituloFinalLayout);
        pnlTituloFinalLayout.setHorizontalGroup(
            pnlTituloFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloFinalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloFinal)
                .addGap(157, 157, 157))
        );
        pnlTituloFinalLayout.setVerticalGroup(
            pnlTituloFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbReporte.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbReporte.setText("Reporte");

        jScrollPane6.setViewportView(txtReporte);

        lbEstadoFinal.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbEstadoFinal.setText("Estado final");

        cmbFinal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione el estado final ...", "Exito", "Fracaso" }));

        btnFinalizar.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFinalizacionLayout = new javax.swing.GroupLayout(pnlFinalizacion);
        pnlFinalizacion.setLayout(pnlFinalizacionLayout);
        pnlFinalizacionLayout.setHorizontalGroup(
            pnlFinalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFinalizacionLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnlFinalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlFinalizacionLayout.createSequentialGroup()
                        .addComponent(lbEstadoFinal)
                        .addGap(18, 18, 18)
                        .addComponent(cmbFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizar))
                    .addGroup(pnlFinalizacionLayout.createSequentialGroup()
                        .addComponent(lbReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        pnlFinalizacionLayout.setVerticalGroup(
            pnlFinalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinalizacionLayout.createSequentialGroup()
                .addComponent(pnlTituloFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlFinalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbReporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pnlFinalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEstadoFinal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFinalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFinalizar)
                        .addComponent(cmbFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );

        tbpSolicitud.addTab("Finalizacion", pnlFinalizacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTituloSolicitudesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSolicitudesMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSolicitudesMouseMoved

    private void btnDocumento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumento1ActionPerformed

        codigo = tblSolicitudes.getSelectedRow();
        String cod = String.valueOf(tblSolicitudes.getValueAt(codigo, 0));

        String[] datos = sql.consultarReparaciones(cod);

        if (cod.equals("")){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro de la tabla", "Atención", JOptionPane.ERROR_MESSAGE);
            tblSolicitudes.requestFocus();
        }
        else
        if (datos != null){

            txtDocSolicitante.setText(datos[0]);
            btnDocumentoActionPerformed(evt);
            txtNumSerie.setText(datos[1]);
            btnNumSerieActionPerformed(evt);
            txtComentarios.setText(datos[3]);
            JOptionPane.showMessageDialog(null, "La solicitud se ha cargado , puede continuar el proceso");
            pestanhas(true, true);
            tbpSolicitud.setSelectedIndex(1);

            int lista = 1;

            if (datos[2].length() == 21){
                lista = 0;
            }

            llenarTabla(lista, datos[2]);

        }

    }//GEN-LAST:event_btnDocumento1ActionPerformed

    private void pnlSolicitanteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSolicitanteMouseMoved

    }//GEN-LAST:event_pnlSolicitanteMouseMoved

    private void pnlTituloMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloMouseMoved

    }//GEN-LAST:event_pnlTituloMouseMoved

    private void btnDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentoActionPerformed

        String[] datos = sql.consultarUsuario(txtDocSolicitante.getText());

        txtNombres.setText(datos[0]);
        txtApellidos.setText(datos[1]);
        txtEmail.setText(datos[2]);
        txtDpto.setText(datos[3]);

    }//GEN-LAST:event_btnDocumentoActionPerformed

    private void pnlArticuloMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlArticuloMouseMoved

    }//GEN-LAST:event_pnlArticuloMouseMoved

    private void pnlTituloArtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloArtMouseMoved

    }//GEN-LAST:event_pnlTituloArtMouseMoved

    private void rbPortatilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbPortatilMouseClicked

    }//GEN-LAST:event_rbPortatilMouseClicked

    private void rbPortatilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPortatilActionPerformed

    }//GEN-LAST:event_rbPortatilActionPerformed

    private void rdComputadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdComputadorActionPerformed

    }//GEN-LAST:event_rdComputadorActionPerformed

    private void rdImpresoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdImpresoraMouseClicked

    }//GEN-LAST:event_rdImpresoraMouseClicked

    private void rdImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdImpresoraActionPerformed

    }//GEN-LAST:event_rdImpresoraActionPerformed

    private void btnNumSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumSerieActionPerformed

        String[] datos = sql.consultarArticulos(txtNumSerie.getText());

        txtMarca.setText(datos[1]);
        txtModelo.setText(datos[2]);

        switch (datos[0]) {
            case "1":
            rbPortatil.setSelected(true);
            lbPortatil.setIcon(new ImageIcon("src/imagenes/portatil.png"));
            lbImpresora.setIcon(new ImageIcon("src/imagenes/impresoraGris.png"));
            lbComputador.setIcon(new ImageIcon("src/imagenes/computadorGris.png"));
            break;
            case "2":
            rdComputador.setSelected(true);
            lbPortatil.setIcon(new ImageIcon("src/imagenes/portatilGris.png"));
            lbImpresora.setIcon(new ImageIcon("src/imagenes/impresoraGris.png"));
            lbComputador.setIcon(new ImageIcon("src/imagenes/computador.png"));
            break;
            default:
            rdImpresora.setSelected(true);
            lbPortatil.setIcon(new ImageIcon("src/imagenes/portatilGris.png"));
            lbImpresora.setIcon(new ImageIcon("src/imagenes/impresora.png"));
            lbComputador.setIcon(new ImageIcon("src/imagenes/computadorGris.png"));
            break;

        }
    }//GEN-LAST:event_btnNumSerieActionPerformed

    private void pnlTituloFallosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloFallosMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloFallosMouseMoved

    private void pnlTituloCompoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloCompoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloCompoMouseMoved

    private void tblComponentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComponentesMouseClicked

        txtFiltrador.setText((String) tblComponentes.getValueAt(tblComponentes.getSelectedRow(), 1));
        lbId.setText(String.valueOf(tblComponentes.getSelectedRow()));
        txtCantidad.setText("0");

    }//GEN-LAST:event_tblComponentesMouseClicked

    private void tblComponentesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComponentesMousePressed
        tblComponentesMouseClicked(evt);
    }//GEN-LAST:event_tblComponentesMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String numExistencia = (String) tblComponentes.getValueAt(Integer.parseInt(lbId.getText()), 4);
            txtFiltrador.setText((String) tblComponentes.getValueAt(Integer.parseInt(lbId.getText()), 1));

            try {
                int cantidad = Integer.parseInt(txtCantidad.getText());

                if (cantidad == 0){
                    JOptionPane.showMessageDialog(null, "Ingrese una cantidad necesaria para la reparación");
                    txtCantidad.requestFocus();
                }
                else if (Integer.parseInt(numExistencia) < cantidad){
                    JOptionPane.showMessageDialog(null, "Ingrese una cantidad igual o menor a la existencia del componente");
                    txtCantidad.requestFocus();
                }
                else {
                    Object[] fila = new Object[5];

                    for (int i = 0; i < 4; i++){
                        fila[i] = tblComponentes.getValueAt(tblComponentes.getSelectedRow(), i);
                    }

                    int sw[] = comprobar(fila[0]);

                    if (sw[0] == 0){

                        fila[4] = cantidad;

                        String valorFinal = String.valueOf(Integer.parseInt(numExistencia) - cantidad);
                        tblComponentes.setValueAt(valorFinal, tblComponentes.getSelectedRow(), 4);

                        DefaultTableModel miModelo = (DefaultTableModel)this.tblCompoAnha.getModel();
                        miModelo.addRow(fila);

                        txtFiltrador.setText("");
                        txtCantidad.setText("");
                        lbId.setText("");
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "El componente ya fue añadido");
                    }

                }
            }
            catch (NumberFormatException | HeadlessException ev){
                JOptionPane.showMessageDialog(null, "Ingrese la cantidad necesitada para la reparación");
                txtCantidad.requestFocus();
            }
        }
        catch (NumberFormatException | HeadlessException ev){
            JOptionPane.showMessageDialog(null, "Seleccione el componente que va a añadir");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFiltradorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltradorKeyReleased

        DefaultTableModel modelo = (DefaultTableModel)tblComponentes.getModel();
        TableRowSorter sorter = new TableRowSorter(modelo);
        tblComponentes.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)^"+ txtFiltrador.getText(), 1));

    }//GEN-LAST:event_txtFiltradorKeyReleased

    private void txtCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusGained

        if (txtCantidad.getText().equals("0")){
            txtCantidad.setText("");
        }

    }//GEN-LAST:event_txtCantidadFocusGained

    private void pnlTituloFinalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloFinalMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloFinalMouseMoved

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

        String componentes = "";
        String reporte = txtReporte.getText();
        String estado = (String) cmbFinal.getSelectedItem();

        for (int i = 0; i < tblCompoAnha.getRowCount(); i++){
            componentes += (String) tblCompoAnha.getValueAt(i, 0) + " " + String.valueOf((Integer) tblCompoAnha.getValueAt(i, 4)) + " ";
        }

        if (componentes.equals("")){
            int option = JOptionPane.showConfirmDialog(rootPane, "No ingresó registro de componentes, ¿desea continuar sin agregarlos?");

            if(option == JOptionPane.YES_OPTION){
                finalizarReparacion(reporte, estado, componentes);
            }
            else if(option == JOptionPane.NO_OPTION){
                tbpSolicitud.setSelectedIndex(4);
            }
        }
        else {
            finalizarReparacion(reporte, estado, componentes);
            tablaCompo();
        }

    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void tbpSolicitudMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpSolicitudMouseMoved

    }//GEN-LAST:event_tbpSolicitudMouseMoved

    private void mnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEliminarActionPerformed

        DefaultTableModel miModelo = (DefaultTableModel)this.tblCompoAnha.getModel();

        int[] sw = comprobar(comprobar(tblCompoAnha.getValueAt(tblCompoAnha.getSelectedRow(), 0)));

        Object numExistencia = (String) tblComponentes.getValueAt(sw[1], 4);
        Object cantidad =  tblCompoAnha.getValueAt(tblCompoAnha.getSelectedRow(), 4);

        String valorFinal = String.valueOf(Integer.parseInt((String)numExistencia) + (Integer)cantidad);

        tblComponentes.setValueAt(valorFinal, sw[1], 4);
        miModelo.removeRow(tblCompoAnha.getSelectedRow());
    }//GEN-LAST:event_mnEliminarActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        validar.soloNumeros(evt);
    }//GEN-LAST:event_txtCantidadKeyTyped

    
    
    //Procedimiento para dar colores al formulario
    private void formColores (String color1, String color2, String color3) 
    {
        this.getContentPane().setBackground(new Color(Integer.parseInt(color2, 16)));
        tbpSolicitud.setBackground(new Color(Integer.parseInt(color1, 16)));
        
        pnlSolicitante.setBackground(new Color(Integer.parseInt(color1, 16)));
        pnlTitulo.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTitulo.setForeground(new Color(Integer.parseInt(color3, 16)));
        
        pnlArticulo.setBackground(new Color(Integer.parseInt(color1, 16)));
        pnlTituloArt.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTituloArt.setForeground(new Color(Integer.parseInt(color3, 16)));   
        
        pnlSolicitud.setBackground(new Color(Integer.parseInt(color1, 16)));
        pnlTituloFallos.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTituloFallos.setForeground(new Color(Integer.parseInt(color3, 16))); 
        
        pnlFallos.setBackground(new Color(Integer.parseInt(color1, 16)));
        pnlTituloSolicitudes.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTituloSolicitudes.setForeground(new Color(Integer.parseInt(color3, 16)));  
        
        pnlFinalizacion.setBackground(new Color(Integer.parseInt(color1, 16)));
        pnlTituloFinal.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTituloFinal.setForeground(new Color(Integer.parseInt(color3, 16))); 
        
        pnlComponentes.setBackground(new Color(Integer.parseInt(color1, 16)));
        pnlTituloCompo.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTituloCompo.setForeground(new Color(Integer.parseInt(color3, 16))); 
    }
     
    private void llenarSolicitudes (){
 
        DefaultTableModel miModelo = (DefaultTableModel)this.tblSolicitudes.getModel();
        
        ArrayList<Object[]> data = sql.tablaSolicitudes(usuarioLogin.texto);
        
            for (int i = 0; i < data.size(); i++){
                miModelo.addRow(data.get(i));
            }
        
         tblSolicitudes.setRowHeight(25);
    }
    
    //Procedimiento para llenar la tabla de chequeo
    private void llenarTabla (int opcion, String chequeo)
    {
  
        int i = 0;
        
       Object[] lista1 =  {"¿El equipo presenta algún tipo de corto?",
            "¿El ordenador enciende , pero no da video?",
            "¿El ordenador se calienta mucho ó produce un ruido intenso?",
            "¿El ordenador sufrió algún tipo de golpe ó caida?",
            "¿La pantalla del equipo sufrió algún tipo de daño?",
            "¿El ordenador presenta problemas en el teclado, touch ó mouse?",
            "¿El ordenador no reproduce ningún tipo de sonido?",
            "¿El ordenador no reconoce unidades ópticas ó usb?",
            "¿Los ventiladores del equipo no encienden?",
            "¿El sistema operativo no inicia ó tarda mucho en iniciar",
            "¿El computador no se conecta a internet?",
            "¿El Computador sufre pausas continuas ó lentitud prolongada?",
            "¿El ordenador se reinicia ó se apaga de forma inesperada?",
            "¿El ordenador presenta problemas con alguna aplicación?",
            "¿El ordenador no se conecta a la red local de la empresa?",
            "¿El ordenador presenta pantallas azules?",
            "¿El ordenador presenta un pitido recurrente?",
            "¿El oomputador presenta perdidas de archivos?",
            "¿El ordenador no deja almacenar achivos nuevos?",
            "¿No aparece laa unidad de cd/dvd?",
            "¿Alguna aplicación presenta problemas de licencia?",
            "¿Hay problemas para ejecutar algún tipo de archivos y/ó aplicación?",
            "¿La bateria del ordenador ya no retiene carga ó dura muy poco?",
            "¿La unidad de cd/dvd se traba?",
            "¿La pantalla enciende y apaga constantemente?"};
        
       Object[] lista2 = {"¿la impresora no enciende?",
                "¿Los ordenadores no reconocen la impresora?",
                "¿La impresora emana humo blanco al imprimir?",
                "¿El papel se atasca en la impresora?",
                "¿La impresora solo imprime parte de la página ó es difusa?",
                "¿La impresora tarda mucho en imprimir?",
                "¿Las impresiones desvordan el papel?",
                "¿Las impresiones presentan manchas ó excesos de tinta?",
                "¿La impresora devulve papel constantemente?",
                "¿Cuando se imprimen multiples copias la impresora se pega ó se atasca?",
                "¿La impresora se apaga de manera imprevista?",
                "¿La impresora tiene prolemas de energía?",
                "¿La impresora presenta un sonido fuerte y constante cuando está imprimiendo?",
                "¿La impresora no imprime?",
                "¿La impresora toma varias hojas a la vez?",
                "¿La impresora solo imprime parte de la información?",
                "¿La impresora confunde colores?",
                "¿La impresora no hace las notificaciones pertinentes?",
                "¿La impresora tiene problemas para conectarse a la red?",
                "¿La impresora se recalienta?",
                "¿La impresora realiza acciones indebidas?"};
       
       tblChequeo.setModel(new DefaultTableModel());
       
       DefaultTableModel miModelo = (DefaultTableModel)this.tblChequeo.getModel();
       
       miModelo.addColumn("Fallo");
       
       Object[] objeto = new Object[1];
       
       if (opcion == 1){
           for (i = 0; i < 25; i++){
               if (chequeo.charAt(i) == '1'){
                   objeto[0] = lista1[i];
                   miModelo.addRow(objeto);
               }
           }
       }
       else {
           for (i = 0; i < 21; i++){
               if (chequeo.charAt(i) == '1'){
                   objeto[0] = lista2[i];
                   miModelo.addRow(objeto);
               }
           }
       }
       
    }
    
    private void llenarTabla ()
    {
        
        DefaultTableModel miModelo = (DefaultTableModel)this.tblComponentes.getModel();
        
        ArrayList<Object[]> data = sql.tablaComponentes();
        
            for (int i = 0; i < data.size(); i++){
                miModelo.addRow(data.get(i));
            }
        
       tblComponentes.setRowHeight(25);
    }
    
    private void camposArticulos () {
        lbPortatil.setIcon(new ImageIcon("src/imagenes/portatilGris.png"));      
        lbImpresora.setIcon(new ImageIcon("src/imagenes/impresoraGris.png"));  
        lbComputador.setIcon(new ImageIcon("src/imagenes/computadorGris.png"));  
    }    
    
    private String fecha ()
    {
        Calendar Calendario = Calendar.getInstance();
       
        String anho = Integer.toString(Calendario.get(Calendar.YEAR));
        String mes = Integer.toString(Calendario.get(Calendar.MONTH) + 1);
        String dia = Integer.toString(Calendario.get(Calendar.DATE));
        
        return (dia + "/" + mes + "/" + anho);
    }
        
    private int[] comprobar (Object val)
    {
        int i;
        int sw[] = new int [2];
        
        for (i = 0; i < tblCompoAnha.getRowCount(); i++){
            if (tblCompoAnha.getValueAt(i, 0) == val){
                sw[0] = 1;
                sw[1] = i;
            }
        }
        return sw;
    }
    
        private int comprobarFinal (Object val)
    {
        int i;
        int sw = 0;
        
        for (i = 0; i < tblComponentes.getRowCount(); i++){
            if (tblComponentes.getValueAt(i, 0) == val){
                sw = i;
            }
        }
        return sw;
    }
    
    private void finalizarReparacion (String reporte, String estado, String componentes){
        
        if (reporte.equals("")){
           JOptionPane.showMessageDialog(null, "Debe dar el reporte de la reparación", "Atención", JOptionPane.ERROR_MESSAGE);
           txtReporte.requestFocus();
        }
        else if (cmbFinal.getSelectedIndex() == 0){
           JOptionPane.showMessageDialog(null, "Debe seleccionar el estado final de la reparación", "Atención", JOptionPane.ERROR_MESSAGE);
           cmbFinal.requestFocus();
        }
        else {
            String cod = String.valueOf((Integer) tblSolicitudes.getValueAt(codigo, 0));
            
            String miReparacion[] = {cod, reporte, estado, componentes, fecha()};
            
            sql.finalizarReparacion(miReparacion);
            
            DefaultTableModel miModelo = (DefaultTableModel)this.tblSolicitudes.getModel();
            miModelo.removeRow(codigo);
            
            JOptionPane.showMessageDialog(null, "La reparación se finalizó con exito");
            tbpSolicitud.setSelectedIndex(0);
            pestanhas(true, false);
        }
    }
        
     public void tablaCompo ()
     {            
            String[] miComponente = new String[2];
            int tabla;
            
            for (int i = 0; i < tblCompoAnha.getRowCount(); i++){
                miComponente[0] = (String)tblCompoAnha.getValueAt(i, 0);
                tabla = comprobarFinal(miComponente[0]);
                miComponente[1] = (String)tblComponentes.getValueAt(tabla, 4);
                sql.extraerComponente(miComponente);
            }
    }
     
     
    private void pestanhas (boolean x, boolean y)
    {
        tbpSolicitud.setEnabledAt(0, x);
        tbpSolicitud.setEnabledAt(1, y);
        tbpSolicitud.setEnabledAt(2, y);
        tbpSolicitud.setEnabledAt(3, y);
        tbpSolicitud.setEnabledAt(4, y);
        tbpSolicitud.setEnabledAt(5, y);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocumento;
    private javax.swing.JButton btnDocumento1;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnNumSerie;
    private javax.swing.JComboBox cmbFinal;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbCantida;
    private javax.swing.JLabel lbComentarios;
    private javax.swing.JLabel lbComputador;
    private javax.swing.JLabel lbDocSolicitante;
    private javax.swing.JLabel lbDpto;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEstadoFinal;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbImpresora;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbModelo;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbNumSerie;
    private javax.swing.JLabel lbPortatil;
    private javax.swing.JLabel lbReporte;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTituloArt;
    private javax.swing.JLabel lbTituloCompo;
    private javax.swing.JLabel lbTituloFallos;
    private javax.swing.JLabel lbTituloFinal;
    private javax.swing.JLabel lbTituloSolicitudes;
    private javax.swing.JMenuItem mnEliminar;
    private javax.swing.JPanel pnlArticulo;
    private javax.swing.JPanel pnlComponentes;
    private javax.swing.JPanel pnlFallos;
    private javax.swing.JPanel pnlFinalizacion;
    private javax.swing.JPanel pnlSolicitante;
    private javax.swing.JPanel pnlSolicitud;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlTituloArt;
    private javax.swing.JPanel pnlTituloCompo;
    private javax.swing.JPanel pnlTituloFallos;
    private javax.swing.JPanel pnlTituloFinal;
    private javax.swing.JPanel pnlTituloSolicitudes;
    private javax.swing.JPopupMenu ppmTabla;
    private javax.swing.JRadioButton rbPortatil;
    private javax.swing.JRadioButton rdComputador;
    private javax.swing.JRadioButton rdImpresora;
    private javax.swing.JTable tblChequeo;
    private javax.swing.JTable tblCompoAnha;
    private javax.swing.JTable tblComponentes;
    private javax.swing.JTable tblSolicitudes;
    private javax.swing.JTabbedPane tbpSolicitud;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JEditorPane txtComentarios;
    private javax.swing.JTextField txtDocSolicitante;
    private javax.swing.JTextField txtDpto;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFiltrador;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumSerie;
    private javax.swing.JEditorPane txtReporte;
    // End of variables declaration//GEN-END:variables
}
