package formularios;

import clases.SQL;
import clases.listas.estUsuario;
import java.awt.*;
import java.io.*;
import javax.swing.JOptionPane;


public class FrmEntrada extends javax.swing.JFrame {

      usuarioLogueado usuarioLogin = new usuarioLogueado();
      validacionesCampos validar = new validacionesCampos();
      static estUsuario cab = null, ult = null;
          
    public FrmEntrada() {
        initComponents();
        //Centramos formuario en pantalla
        this.setLocationRelativeTo(null);
        //Llamamos procedmiento de colores y mandamos parametros iniciales
        formColores("FFFFFF", "6699ff", "FFFFFF", "000000"); 

        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo3 = new javax.swing.JPanel();
        lbTitulo3 = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbContrasena = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        pnlTitulo3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTitulo3MouseMoved(evt);
            }
        });

        lbTitulo3.setFont(new java.awt.Font("Agency FB", 1, 100)); // NOI18N
        lbTitulo3.setText(" Bufet");

        javax.swing.GroupLayout pnlTitulo3Layout = new javax.swing.GroupLayout(pnlTitulo3);
        pnlTitulo3.setLayout(pnlTitulo3Layout);
        pnlTitulo3Layout.setHorizontalGroup(
            pnlTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitulo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlTitulo3Layout.setVerticalGroup(
            pnlTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitulo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo3, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbUsuario.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbUsuario.setText("*Usuario:");

        lbContrasena.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbContrasena.setText("*Contraseña:");

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });

        btnIngresar.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel1.setText("¿Olvidaste tu contraseña?");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIngresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbContrasena)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContrasena)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTitulo3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitulo3MouseMoved
        formColores("FFFFFF", "6699ff", "FFFFFF", "000000");    
    }//GEN-LAST:event_pnlTitulo3MouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        formColores("6699ff", "FFFFFF", "000000", "FFFFFF");  
    }//GEN-LAST:event_formMouseMoved

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String nombre, contrasena;
        
        nombre = txtUsuario.getText();
        contrasena = txtContrasena.getText();
        
        estUsuario p = cab;
        int sw = 0;
        
        while (p != null || sw == 0){            
            if (nombre.equals(p.usuario) && contrasena.equals(p.contrasena)){
                switch(p.perfil){
                    case "Administrador":
                        FrmAdministrador  formulario = new FrmAdministrador();
                        formulario.show();
                        break;
                    case "Tecnico":
                        FrmAdministrador_1  formularioDos = new FrmAdministrador_1(p);
                        formularioDos.show();
                        break;
                }
                this.setVisible(false);   
                sw = 1;
                usuarioLogin.texto = p.usuario;
                
            }
            p = p.liga;
        }
        
        
        if (this.isVisible()){
            JOptionPane.showMessageDialog(rootPane, "Usuario o contraseña incorrecto");    
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        validar.soloNumeros(evt);
    }//GEN-LAST:event_txtUsuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEntrada().setVisible(true);
            }
        });
    }
    
    
    private void formColores (String color1, String color2, String color3, String color4) 
    {
        this.getContentPane().setBackground(new Color(Integer.parseInt(color1, 16)));
        pnlTitulo3.setBackground(new Color(Integer.parseInt(color2, 16)));
        
        lbTitulo3.setForeground(new Color(Integer.parseInt(color3, 16)));
        lbUsuario.setForeground(new Color(Integer.parseInt(color4, 16)));
        lbContrasena.setForeground(new Color(Integer.parseInt(color4, 16))); 
    }
    
    
    private void cargarDatos ()
    {
        try {
            File f = new File("E:/usuarios.in");
            BufferedReader entrada;
            entrada = new BufferedReader(new FileReader(f));
            String[] nodos = entrada.readLine().split("---"), valores;
            
            estUsuario p;
                        
            for (int i = 0; i < nodos.length; i++){
                p = new estUsuario();
                
                if (p == null){
                    System.out.println("Memoria llena");
                }
                else {
                    valores = nodos[i].split(",");
                    
                    p.usuario = valores[0];
                    p.contrasena = valores[1];
                    p.nombre = valores[2];
                    p.apellido = valores[3];
                    p.email = valores[4];
                    //p.departamento = valores[5];
                    p.perfil = valores[5];
                    p.estado = valores[6];
                    p.fecha = valores[7];
                    
                    if (cab == null){
                        cab = p;
                    }
                    else {
                        ult.liga = p;
                    }
                    ult = p;
                }
            }              
        }
        catch (IOException e){
            System.out.println("Error: " + e);
        }
    }
    
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbContrasena;
    private javax.swing.JLabel lbTitulo3;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPanel pnlTitulo3;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
