/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.SQL;
import clases.listas.estUsuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Cristian Morales
 */
public class FrmAdministrador extends javax.swing.JFrame {

    IfrmSolicitud solicitud;
    IfrmCrudArticulos articulos;
    IfrmCrudComponentes componentes;
    IfrmCrudUsuarios usuarios;
    IfrmCrudEntrega entrega;
    
    usuarioLogueado usuarioLogin = new usuarioLogueado();
    static estUsuario cab = null, ult = null;
    
    public FrmAdministrador() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        
        iconosGrises();
        
        formColores("FFFFFF", "6699ff", "FFFFFF");
        
        pnlAdminstrar.setVisible(false);
        pnlEjecutar.setVisible(false);
        
        cargarDatos();
        
        estUsuario usu = consultarUsuario(usuarioLogin.texto);
        
        //txtMensaje.setText("Bienvenido " + usu.nombre + " a ArtSoft");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        pnlInformacion = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnlMenu = new javax.swing.JPanel();
        pnlTituloAdmin = new javax.swing.JPanel();
        lbTituloAdmin = new javax.swing.JLabel();
        lbExpAdmin = new javax.swing.JLabel();
        pnlTituloEjec = new javax.swing.JPanel();
        lbTituloEjec = new javax.swing.JLabel();
        lbExpEjec = new javax.swing.JLabel();
        pnlAdminstrar = new javax.swing.JPanel();
        iconUsuario = new javax.swing.JLabel();
        iconArt = new javax.swing.JLabel();
        iconComp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlEjecutar = new javax.swing.JPanel();
        iconAsig = new javax.swing.JLabel();
        iconEntrega = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlArtSoft = new javax.swing.JPanel();
        lbArtSoft = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bufete");

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(605, 397));

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton1.setText("Cerrar sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInformacionLayout = new javax.swing.GroupLayout(pnlInformacion);
        pnlInformacion.setLayout(pnlInformacionLayout);
        pnlInformacionLayout.setHorizontalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionLayout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(224, 224, 224))
        );
        pnlInformacionLayout.setVerticalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pnlTituloAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTituloAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTituloAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTituloAdminMouseClicked(evt);
            }
        });

        lbTituloAdmin.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lbTituloAdmin.setText("Administrar");

        lbExpAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N

        javax.swing.GroupLayout pnlTituloAdminLayout = new javax.swing.GroupLayout(pnlTituloAdmin);
        pnlTituloAdmin.setLayout(pnlTituloAdminLayout);
        pnlTituloAdminLayout.setHorizontalGroup(
            pnlTituloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloAdmin)
                .addGap(22, 22, 22)
                .addComponent(lbExpAdmin)
                .addContainerGap())
        );
        pnlTituloAdminLayout.setVerticalGroup(
            pnlTituloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTituloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloAdminLayout.createSequentialGroup()
                        .addComponent(lbTituloAdmin)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloAdminLayout.createSequentialGroup()
                        .addComponent(lbExpAdmin)
                        .addGap(21, 21, 21))))
        );

        pnlTituloEjec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTituloEjec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTituloEjec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTituloEjecMouseClicked(evt);
            }
        });

        lbTituloEjec.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lbTituloEjec.setText("Ejecutar");

        lbExpEjec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N

        javax.swing.GroupLayout pnlTituloEjecLayout = new javax.swing.GroupLayout(pnlTituloEjec);
        pnlTituloEjec.setLayout(pnlTituloEjecLayout);
        pnlTituloEjecLayout.setHorizontalGroup(
            pnlTituloEjecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloEjecLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lbTituloEjec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbExpEjec)
                .addContainerGap())
        );
        pnlTituloEjecLayout.setVerticalGroup(
            pnlTituloEjecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloEjecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloEjecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTituloEjecLayout.createSequentialGroup()
                        .addComponent(lbTituloEjec)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloEjecLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbExpEjec)
                        .addGap(21, 21, 21))))
        );

        pnlAdminstrar.setBackground(new java.awt.Color(204, 204, 255));
        pnlAdminstrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        iconUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconUsuarioMouseClicked(evt);
            }
        });

        iconArt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconArtMouseClicked(evt);
            }
        });

        iconComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconCompMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel1.setText("Usuarios");

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel3.setText("Agenda");

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel4.setText("Expedientes");

        javax.swing.GroupLayout pnlAdminstrarLayout = new javax.swing.GroupLayout(pnlAdminstrar);
        pnlAdminstrar.setLayout(pnlAdminstrarLayout);
        pnlAdminstrarLayout.setHorizontalGroup(
            pnlAdminstrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminstrarLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(pnlAdminstrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminstrarLayout.createSequentialGroup()
                        .addGroup(pnlAdminstrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAdminstrarLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)))
                        .addGap(38, 38, 38)
                        .addGroup(pnlAdminstrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAdminstrarLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addComponent(iconArt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminstrarLayout.createSequentialGroup()
                        .addGroup(pnlAdminstrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(iconComp, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))))
        );
        pnlAdminstrarLayout.setVerticalGroup(
            pnlAdminstrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminstrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminstrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconArt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAdminstrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconComp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pnlEjecutar.setBackground(new java.awt.Color(204, 204, 255));
        pnlEjecutar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        iconAsig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconAsig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconAsigMouseClicked(evt);
            }
        });

        iconEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconEntrega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconEntregaMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel6.setText("Solicitud");

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel7.setText("Entrega");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlEjecutarLayout = new javax.swing.GroupLayout(pnlEjecutar);
        pnlEjecutar.setLayout(pnlEjecutarLayout);
        pnlEjecutarLayout.setHorizontalGroup(
            pnlEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEjecutarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEjecutarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)))
                .addGap(38, 38, 38)
                .addGroup(pnlEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEjecutarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEjecutarLayout.setVerticalGroup(
            pnlEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEjecutarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 3, Short.MAX_VALUE)
                    .addComponent(iconAsig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEjecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlArtSoft.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbArtSoft.setFont(new java.awt.Font("Agency FB", 1, 90)); // NOI18N
        lbArtSoft.setText("Bufete");

        javax.swing.GroupLayout pnlArtSoftLayout = new javax.swing.GroupLayout(pnlArtSoft);
        pnlArtSoft.setLayout(pnlArtSoftLayout);
        pnlArtSoftLayout.setHorizontalGroup(
            pnlArtSoftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArtSoftLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbArtSoft)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlArtSoftLayout.setVerticalGroup(
            pnlArtSoftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArtSoftLayout.createSequentialGroup()
                .addComponent(lbArtSoft, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloEjec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(pnlAdminstrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addComponent(pnlArtSoft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTituloAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlEjecutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlArtSoft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTituloAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAdminstrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTituloEjec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addComponent(pnlInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTituloAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloAdminMouseClicked
        
        if (pnlAdminstrar.isVisible()){
            pnlAdminstrar.setVisible(false);
            lbExpAdmin.setIcon(new ImageIcon("src/imagenes/mas.png"));
        }    
        else {
            pnlAdminstrar.setVisible(true);
            pnlEjecutar.setVisible(false);
            lbExpAdmin.setIcon(new ImageIcon("src/imagenes/menos.png"));
            lbExpEjec.setIcon(new ImageIcon("src/imagenes/mas.png"));
        }
        
    }//GEN-LAST:event_pnlTituloAdminMouseClicked

    private void pnlTituloEjecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloEjecMouseClicked

        if (pnlEjecutar.isVisible()){
            pnlEjecutar.setVisible(false);
            lbExpEjec.setIcon(new ImageIcon("src/imagenes/mas.png"));
        }    
        else {
            pnlAdminstrar.setVisible(false);
            pnlEjecutar.setVisible(true);
            lbExpEjec.setIcon(new ImageIcon("src/imagenes/menos.png"));
            lbExpAdmin.setIcon(new ImageIcon("src/imagenes/mas.png"));
        }
    }//GEN-LAST:event_pnlTituloEjecMouseClicked

    private void iconUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconUsuarioMouseClicked
        
        iconosGrises();
        iconUsuario.setIcon(new ImageIcon("src/imagenes/usuarios.png"));
        
        if(estacerrado(usuarios)){
            
            usuarios = new IfrmCrudUsuarios();
            jDesktopPane1.add(usuarios);
            
            BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane)((BasicInternalFrameUI) usuarios.getUI()).getNorthPane();  
            usuarios.remove(titlePane); 
           
            usuarios.show();
        }
        else{
            try {
                usuarios.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(FrmAdministrador.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_iconUsuarioMouseClicked

    private void iconArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconArtMouseClicked
        
        iconosGrises();
        iconArt.setIcon(new ImageIcon("src/imagenes/articulos.png"));
        
        if(estacerrado(articulos)){        
            articulos = new IfrmCrudArticulos();
            jDesktopPane1.add(articulos);
            
            BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane)((BasicInternalFrameUI) articulos.getUI()).getNorthPane();  
            articulos.remove(titlePane); 
           
            articulos.show();
        }
        else{
            try {
                articulos.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(FrmAdministrador.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_iconArtMouseClicked

    private void iconCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconCompMouseClicked
        
        iconosGrises();
        iconComp.setIcon(new ImageIcon("src/imagenes/componentes.png"));
        
        if(estacerrado(componentes)){
            
            componentes = new IfrmCrudComponentes();
            jDesktopPane1.add(componentes);
            
            BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane)((BasicInternalFrameUI) componentes.getUI()).getNorthPane();  
            componentes.remove(titlePane); 
           
            componentes.show();
        }
        else{
            try {
                componentes.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(FrmAdministrador.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_iconCompMouseClicked

    private void iconAsigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAsigMouseClicked
            iconosGrises();
        iconAsig.setIcon(new ImageIcon("src/imagenes/asignacion.png"));
        
        if(estacerrado(solicitud)){
            
            solicitud = new IfrmSolicitud();
            jDesktopPane1.add(solicitud);
            
            BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane)((BasicInternalFrameUI) solicitud.getUI()).getNorthPane();  
            solicitud.remove(titlePane); 
           
            solicitud.show();
        }
        else{
            try {
                solicitud.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(FrmAdministrador.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    
    }//GEN-LAST:event_iconAsigMouseClicked

  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmEntrada formulario = new FrmEntrada();
        formulario.setVisible(true);
        
        this.dispose();
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       iconosGrises();
        iconEntrega.setIcon(new ImageIcon("src/imagenes/salida.png"));
        
        if(estacerrado(entrega)){
            
            entrega = new IfrmCrudEntrega();
            jDesktopPane1.add(entrega);
            
            BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane)((BasicInternalFrameUI) entrega.getUI()).getNorthPane();  
            entrega.remove(titlePane); 
           
            entrega.show();
        }
        else{
            try {
               entrega.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(FrmAdministrador.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_jLabel7MouseClicked
 
   
    private void iconEntregaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconEntregaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconEntregaMouseClicked

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrador().setVisible(true);
            }
        });
    }
    
    public void iconosGrises (){
        iconUsuario.setIcon(new ImageIcon("src/imagenes/usuariosGris.png"));
        iconArt.setIcon(new ImageIcon("src/imagenes/articulosGris.png"));
        iconComp.setIcon(new ImageIcon("src/imagenes/componentesGris.png"));
        //iconReg.setIcon(new ImageIcon("src/imagenes/registrosGris.png"));
        iconAsig.setIcon(new ImageIcon("src/imagenes/asignacionGris.png"));
        iconEntrega.setIcon(new ImageIcon("src/imagenes/salidaGris.png"));
    }
    
    private void formColores (String color1, String color2, String color3) 
    {
        this.getContentPane().setBackground(new Color(Integer.parseInt(color1, 16)));
        pnlMenu.setBackground(new Color(Integer.parseInt(color1, 16)));
        
        pnlArtSoft.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbArtSoft.setForeground(new Color(Integer.parseInt(color3, 16)));
        
        //pnlAdminstrar.setBackground(new Color(Integer.parseInt(color1, 16)));
        
        pnlTituloAdmin.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTituloAdmin.setForeground(new Color(Integer.parseInt(color3, 16)));   
        
        pnlInformacion.setBackground(new Color(Integer.parseInt(color1, 16)));
        
        pnlTituloEjec.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTituloEjec.setForeground(new Color(Integer.parseInt(color3, 16)));   
    }
     
    
    public boolean estacerrado(Object obj){
        JInternalFrame[] activos  = jDesktopPane1.getAllFrames();
        boolean cerrado=true;
        int i = 0;
        
        while (i<activos.length && cerrado){
            if(activos[i]==obj){
                    cerrado=false;
            }
            i++;
        }
        return cerrado;
    }    

    private void cargarDatos() {
        try {
            File f = new File("D:/usuarios.in");
            BufferedReader entrada;
            entrada = new BufferedReader(new FileReader(f));
            String[] nodos = entrada.readLine().split("---"), valores;

            estUsuario p;

            for (int i = 0; i < nodos.length; i++) {
                p = new estUsuario();

                if (p == null) {
                    System.out.println("Memoria llena");
                } else {
                    valores = nodos[i].split(",");

                    p.usuario = valores[0];
                    p.contrasena = valores[1];
                    p.nombre = valores[2];
                    p.apellido = valores[3];
                    p.email = valores[4];
                   // p.departamento = valores[5];
                    p.perfil = valores[5];
                    p.estado = valores[6];
                    p.fecha = valores[7];

                    if (cab == null) {
                        cab = p;
                    } else {
                        ult.liga = p;
                    }
                    ult = p;
                }
            }
        } catch (IOException e) {
            System.out.println("Error: " + e);
        }
    }

    private estUsuario consultarUsuario(String usuario) {
        estUsuario p = cab;

        while (p != null) {
            if (p.usuario.equals(usuario)) {
                return p;
            }
            p = p.liga;
        }
        return null;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconArt;
    private javax.swing.JLabel iconAsig;
    private javax.swing.JLabel iconComp;
    private javax.swing.JLabel iconEntrega;
    private javax.swing.JLabel iconUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbArtSoft;
    private javax.swing.JLabel lbExpAdmin;
    private javax.swing.JLabel lbExpEjec;
    private javax.swing.JLabel lbTituloAdmin;
    private javax.swing.JLabel lbTituloEjec;
    private javax.swing.JPanel pnlAdminstrar;
    private javax.swing.JPanel pnlArtSoft;
    private javax.swing.JPanel pnlEjecutar;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTituloAdmin;
    private javax.swing.JPanel pnlTituloEjec;
    // End of variables declaration//GEN-END:variables
}
