/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.SQL;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Cristian Morales
 */
public class FrmSolicitante extends javax.swing.JFrame {

    IfrmFinalizacion solicitud;
    IfrmCrudArticulos componentes;
    IfrmCrudUsuarios usuarios;
    
    usuarioLogueado usuarioLogin = new usuarioLogueado();
    SQL sql = new SQL ();
    
    public FrmSolicitante() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        
        formColores("FFFFFF", "6699ff", "FFFFFF");

        
        String usu[] = sql.consultarUsuario(usuarioLogin.texto);
        
        txtMensaje.setText("Bienvenido " + usu[0] + " a ArtSoft");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        pnlInformacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlMenu = new javax.swing.JPanel();
        pnlTituloAdmin = new javax.swing.JPanel();
        lbTituloAdmin = new javax.swing.JLabel();
        lbExpAdmin = new javax.swing.JLabel();
        pnlAdminstrar = new javax.swing.JPanel();
        iconComp = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlArtSoft = new javax.swing.JPanel();
        lbArtSoft = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ArtSoft - Software en el manejo de articulos");

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(605, 397));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.png"))); // NOI18N

        txtMensaje.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        txtMensaje.setText("jLabel8");

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton1.setText("Cerrar sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInformacionLayout = new javax.swing.GroupLayout(pnlInformacion);
        pnlInformacion.setLayout(pnlInformacionLayout);
        pnlInformacionLayout.setHorizontalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(pnlInformacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(32, 32, 32))
        );
        pnlInformacionLayout.setVerticalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlTituloAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTituloAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTituloAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTituloAdminMouseClicked(evt);
            }
        });

        lbTituloAdmin.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lbTituloAdmin.setText("Consultar");

        lbExpAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N

        javax.swing.GroupLayout pnlTituloAdminLayout = new javax.swing.GroupLayout(pnlTituloAdmin);
        pnlTituloAdmin.setLayout(pnlTituloAdminLayout);
        pnlTituloAdminLayout.setHorizontalGroup(
            pnlTituloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloAdmin)
                .addGap(39, 39, 39)
                .addComponent(lbExpAdmin)
                .addContainerGap())
        );
        pnlTituloAdminLayout.setVerticalGroup(
            pnlTituloAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbExpAdmin)
                .addGap(21, 21, 21))
            .addGroup(pnlTituloAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAdminstrar.setBackground(new java.awt.Color(204, 204, 255));
        pnlAdminstrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        iconComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registros.png"))); // NOI18N
        iconComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconCompMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel4.setText("Registros");

        javax.swing.GroupLayout pnlAdminstrarLayout = new javax.swing.GroupLayout(pnlAdminstrar);
        pnlAdminstrar.setLayout(pnlAdminstrarLayout);
        pnlAdminstrarLayout.setHorizontalGroup(
            pnlAdminstrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminstrarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlAdminstrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconComp)
                    .addGroup(pnlAdminstrarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        pnlAdminstrarLayout.setVerticalGroup(
            pnlAdminstrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminstrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconComp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pnlArtSoft.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbArtSoft.setFont(new java.awt.Font("Agency FB", 1, 90)); // NOI18N
        lbArtSoft.setText("ArtSoft");

        javax.swing.GroupLayout pnlArtSoftLayout = new javax.swing.GroupLayout(pnlArtSoft);
        pnlArtSoft.setLayout(pnlArtSoftLayout);
        pnlArtSoftLayout.setHorizontalGroup(
            pnlArtSoftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArtSoftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbArtSoft)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlArtSoftLayout.setVerticalGroup(
            pnlArtSoftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArtSoftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbArtSoft, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(pnlAdminstrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnlArtSoft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTituloAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlArtSoft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTituloAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAdminstrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addComponent(pnlInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTituloAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloAdminMouseClicked
        
    }//GEN-LAST:event_pnlTituloAdminMouseClicked

    private void iconCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconCompMouseClicked

    }//GEN-LAST:event_iconCompMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        FrmEntrada formulario = new FrmEntrada();
        formulario.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSolicitante().setVisible(true);
            }
        });
        
        /*        */
        
    }

        private void formColores (String color1, String color2, String color3) 
    {
        this.getContentPane().setBackground(new Color(Integer.parseInt(color1, 16)));
        pnlMenu.setBackground(new Color(Integer.parseInt(color1, 16)));
        
        pnlArtSoft.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbArtSoft.setForeground(new Color(Integer.parseInt(color3, 16)));
        
        //pnlAdminstrar.setBackground(new Color(Integer.parseInt(color1, 16)));
        
        pnlTituloAdmin.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTituloAdmin.setForeground(new Color(Integer.parseInt(color3, 16)));   
        
        pnlInformacion.setBackground(new Color(Integer.parseInt(color1, 16)));

    }
     
    
    public boolean estacerrado(Object obj){
        JInternalFrame[] activos  = jDesktopPane1.getAllFrames();
        boolean cerrado=true;
        int i = 0;
        
        while (i<activos.length && cerrado){
            if(activos[i]==obj){
                    cerrado=false;
            }
            i++;
        }
        return cerrado;
    }    
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconComp;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbArtSoft;
    private javax.swing.JLabel lbExpAdmin;
    private javax.swing.JLabel lbTituloAdmin;
    private javax.swing.JPanel pnlAdminstrar;
    private javax.swing.JPanel pnlArtSoft;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTituloAdmin;
    private javax.swing.JLabel txtMensaje;
    // End of variables declaration//GEN-END:variables
}
