package formularios;

import clases.SQL;
import clases.listas.estArticulo;
import clases.listas.estUsuario;
import java.awt.Color;
import java.io.*;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class IfrmCrudArticulos extends javax.swing.JInternalFrame {

    //SQL sql = new SQL();
    usuarioLogueado usuarioLogin = new usuarioLogueado();
    validacionesCampos validar = new validacionesCampos();
    
    static estArticulo cab = null, ult = null;

    public IfrmCrudArticulos() {
        initComponents();

        //String usu[] = sql.consultarUsuario(usuarioLogin.texto);

        cargarDatos();

        /*
         * if (!usu[4].equals("Administrador")){ btnEliminar.setVisible(false);
         * btnModificar.setVisible(false); btnNuevo.setVisible(false);
         * btnRegistrar.setVisible(false); txtFiltrador.setVisible(false);
         *
         * DefaultTableModel modelo = (DefaultTableModel)tblUsuarios.getModel();
         * TableRowSorter sorter = new TableRowSorter(modelo);
         * tblUsuarios.setRowSorter(sorter);
         * sorter.setRowFilter(RowFilter.regexFilter("(?i)^"+
         * usuarioLogin.texto, 0));
         *
         * modelo.removeRow(0); }
         */

        formColores("FFFFFF", "6699ff", "FFFFFF");
        tbpSolicitud.setTabPlacement(tbpSolicitud.BOTTOM);

        txtFiltrador.requestFocus();
        llenarTabla();
        botones(false);
        camposArticulos();

     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        tbpSolicitud = new javax.swing.JTabbedPane();
        pnlTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        pnlTituloTabla = new javax.swing.JPanel();
        lbTituloTabla = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtFiltrador = new javax.swing.JTextField();
        pnlArticulo = new javax.swing.JPanel();
        pnlTituloArt = new javax.swing.JPanel();
        lbTituloArt = new javax.swing.JLabel();
        lbNumSerie = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        lbTipo = new javax.swing.JLabel();
        lbMarca = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lbModelo = new javax.swing.JLabel();
        txtHoraI = new javax.swing.JTextField();
        lbImpresora = new javax.swing.JLabel();
        pnlBotonesArticulo = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lbFecha = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        lbNumSerie1 = new javax.swing.JLabel();
        TxtHT = new javax.swing.JTextField();
        txtFe = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(70, 56));

        tbpSolicitud.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        tbpSolicitud.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tbpSolicitudMouseMoved(evt);
            }
        });

        pnlTabla.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTablaMouseMoved(evt);
            }
        });

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lugar", "Fecha", "Hora_Inicio", "Hora_Final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        pnlTituloTabla.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloTablaMouseMoved(evt);
            }
        });

        lbTituloTabla.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        lbTituloTabla.setText("Agenda");

        javax.swing.GroupLayout pnlTituloTablaLayout = new javax.swing.GroupLayout(pnlTituloTabla);
        pnlTituloTabla.setLayout(pnlTituloTablaLayout);
        pnlTituloTablaLayout.setHorizontalGroup(
            pnlTituloTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloTablaLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(lbTituloTabla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloTablaLayout.setVerticalGroup(
            pnlTituloTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton1.setText("Transferir al formulario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtFiltrador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltradorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(pnlTituloTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(txtFiltrador, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap())
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaLayout.createSequentialGroup()
                .addComponent(pnlTituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        tbpSolicitud.addTab("Tabla", pnlTabla);

        pnlArticulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlArticuloMouseMoved(evt);
            }
        });

        pnlTituloArt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloArtMouseMoved(evt);
            }
        });

        lbTituloArt.setFont(new java.awt.Font("Agency FB", 1, 70)); // NOI18N
        lbTituloArt.setText("Agenda");

        javax.swing.GroupLayout pnlTituloArtLayout = new javax.swing.GroupLayout(pnlTituloArt);
        pnlTituloArt.setLayout(pnlTituloArtLayout);
        pnlTituloArtLayout.setHorizontalGroup(
            pnlTituloArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloArtLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(lbTituloArt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloArtLayout.setVerticalGroup(
            pnlTituloArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloArtLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloArt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbNumSerie.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbNumSerie.setText("*Lugar");

        txtLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLugarActionPerformed(evt);
            }
        });
        txtLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLugarKeyTyped(evt);
            }
        });

        lbTipo.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbTipo.setText("Titulo");

        lbMarca.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbMarca.setText("Descripción");

        lbModelo.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbModelo.setText("*Hora inicio");

        pnlBotonesArticulo.setBackground(new java.awt.Color(255, 255, 255));

        btnNuevo.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesArticuloLayout = new javax.swing.GroupLayout(pnlBotonesArticulo);
        pnlBotonesArticulo.setLayout(pnlBotonesArticuloLayout);
        pnlBotonesArticuloLayout.setHorizontalGroup(
            pnlBotonesArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesArticuloLayout.createSequentialGroup()
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBotonesArticuloLayout.setVerticalGroup(
            pnlBotonesArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnNuevo)
                .addComponent(btnModificar)
                .addComponent(btnEliminar)
                .addComponent(btnRegistrar))
        );

        lbFecha.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbFecha.setText("*Fecha");

        lbEstado.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbEstado.setText("*Hora terminación");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTituloKeyTyped(evt);
            }
        });

        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoKeyTyped(evt);
            }
        });

        lbNumSerie1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lbNumSerie1.setText("*Estado");

        txtFe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlArticuloLayout = new javax.swing.GroupLayout(pnlArticulo);
        pnlArticulo.setLayout(pnlArticuloLayout);
        pnlArticuloLayout.setHorizontalGroup(
            pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlArticuloLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotonesArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlArticuloLayout.createSequentialGroup()
                                .addComponent(lbMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescripcion))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlArticuloLayout.createSequentialGroup()
                                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                                        .addComponent(lbNumSerie1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbNumSerie)
                                            .addComponent(lbTipo))
                                        .addGap(24, 24, 24)
                                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtLugar, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                            .addComponent(txtTitulo))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbFecha)
                                    .addComponent(lbEstado)
                                    .addComponent(lbModelo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHoraI, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(TxtHT)
                                    .addComponent(txtFe))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlArticuloLayout.setVerticalGroup(
            pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArticuloLayout.createSequentialGroup()
                .addComponent(pnlTituloArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNumSerie))
                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlArticuloLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lbImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlArticuloLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNumSerie1)))))
                    .addGroup(pnlArticuloLayout.createSequentialGroup()
                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHoraI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlBotonesArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tbpSolicitud.addTab("Formulario", pnlArticulo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTituloTablaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloTablaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloTablaMouseMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String codigo = String.valueOf(tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 0));

        estArticulo nodoArticulo = consultarArticulo(codigo);

        if (codigo.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro de la tabla", "Atención", JOptionPane.ERROR_MESSAGE);
            txtFiltrador.requestFocus();
        } else if (nodoArticulo != null) {
            txtLugar.setText(codigo);
            txtDescripcion.setText(nodoArticulo.descripcion);
            txtHoraI.setText(nodoArticulo.horaI);
            TxtHT.setText(nodoArticulo.fecha);
            txtFe.setText(nodoArticulo.horaF);
            txtTitulo.setText(nodoArticulo.titulo);
            txtEstado.setText(nodoArticulo.estado);
         
           

            tbpSolicitud.setSelectedIndex(1);
            txtLugar.setEditable(false);
            botones(true);
            btnRegistrar.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFiltradorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltradorKeyReleased

        DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();
        TableRowSorter sorter = new TableRowSorter(modelo);
        tblUsuarios.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)^" + txtFiltrador.getText(), 0));
    }//GEN-LAST:event_txtFiltradorKeyReleased

    private void pnlTablaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTablaMouseMoved
    }//GEN-LAST:event_pnlTablaMouseMoved

    private void pnlTituloArtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloArtMouseMoved
    }//GEN-LAST:event_pnlTituloArtMouseMoved

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        camposArticulos();
        botones(false);
        btnRegistrar.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        String Lugar = txtLugar.getText();
        String Descripcion = txtDescripcion.getText();
        String horaI = txtHoraI.getText();
        String fecha = txtFe.getText();
        String horaF = TxtHT.getText();
        String titulo = txtTitulo.getText();
        String estado = txtEstado.getText();

       

        if (consultarArticulo(Lugar) != null) {
            JOptionPane.showMessageDialog(null, "la ageda  ya esta registrado", "Atención", JOptionPane.ERROR_MESSAGE);
            txtLugar.requestFocus();
        } else if (Lugar.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de lugar", "Atención", JOptionPane.ERROR_MESSAGE);
            txtLugar.requestFocus();
        } else if (horaF.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de hora final", "Atención", JOptionPane.ERROR_MESSAGE);
            TxtHT.requestFocus();
        } else if (horaI.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de hora de inicio", "Atención", JOptionPane.ERROR_MESSAGE);
            txtHoraI.requestFocus();
        } else if (fecha.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta llenar el campo de fecha", "Atención", JOptionPane.ERROR_MESSAGE);
           txtFe.requestFocus();
        } else {
                
            

            String registro = "---" + Lugar + "," + titulo + "," + fecha + "," + horaF + "," + horaI
                    + ","  + Descripcion + "Activo"+","+"0";
           
            nuevoArticulo(registro);
              
            String miFila[] = {Lugar, fecha, horaF, horaI};
            DefaultTableModel miTabla = (DefaultTableModel) this.tblUsuarios.getModel();
            miTabla.addRow(miFila);

            JOptionPane.showMessageDialog(null, "La agenda fue registrada con exito");

            btnNuevoActionPerformed(evt);

            estArticulo p = new estArticulo();

            p.lugar = Lugar;
            p.descripcion = Descripcion;
            p.horaF = horaF;
            p.fecha = fecha;
            p.horaI = horaI;          
            p.titulo= titulo;
            p.estado= estado;

            ult.liga = p;
            ult = p;
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        String lugar = txtLugar.getText();
        String descrpcion = txtDescripcion.getText();
        String horaI = txtHoraI.getText();
        String fecha= txtFe.getText();
        String horaF= TxtHT.getText();
        String titulo= txtTitulo.getText();
        String estado = txtEstado.getText();
        
        

        if (horaI.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de hora final", "Atención", JOptionPane.ERROR_MESSAGE);
            txtHoraI.requestFocus();
        } else if (horaF.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de hora final", "Atención", JOptionPane.ERROR_MESSAGE);
            TxtHT.requestFocus();
        }else if (fecha.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta  llenar el campo de fecha", "Atención", JOptionPane.ERROR_MESSAGE);
            txtFe.requestFocus(); 
        }else {

            btnNuevoActionPerformed(evt);

            String miFila[] = {lugar,fecha, horaI, horaF,titulo,descrpcion,"0"};
            DefaultTableModel miTabla = (DefaultTableModel) this.tblUsuarios.getModel();
            miTabla.removeRow(tblUsuarios.getSelectedRow());
            miTabla.addRow(miFila);

            estArticulo p = consultarArticulo(lugar);
            
            p.lugar = lugar;
            p.horaI= horaI;
            p.horaF = horaF;
            p.fecha = fecha;
            p.descripcion = descrpcion;
            p.estado= estado;

            modRegistro();
            JOptionPane.showMessageDialog(null, "El artículo fue modificado con exito");
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        String Articulo = txtLugar.getText();

        int option = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de que desea cambiar el estado del artículo?");

        if (option == JOptionPane.YES_OPTION) {
            estArticulo p = consultarArticulo(Articulo);
            p.estado= "Inactivo";
            modRegistro();
            txtEstado.setText("Inactivo");
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void pnlArticuloMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlArticuloMouseMoved
    }//GEN-LAST:event_pnlArticuloMouseMoved

    private void tbpSolicitudMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpSolicitudMouseMoved
    }//GEN-LAST:event_tbpSolicitudMouseMoved

    private void txtLugarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarKeyTyped
      
    }//GEN-LAST:event_txtLugarKeyTyped

    private void txtLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugarActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloKeyTyped

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoKeyTyped

    private void txtFeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeActionPerformed

    //Procedimiento para dar colores al formulario
    private void formColores(String color1, String color2, String color3) {
        this.getContentPane().setBackground(new Color(Integer.parseInt(color2, 16)));
        pnlArticulo.setBackground(new Color(Integer.parseInt(color1, 16)));
        pnlTabla.setBackground(new Color(Integer.parseInt(color1, 16)));
        tbpSolicitud.setBackground(new Color(Integer.parseInt(color1, 16)));

        pnlTituloArt.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTituloArt.setForeground(new Color(Integer.parseInt(color3, 16)));

        pnlTituloTabla.setBackground(new Color(Integer.parseInt(color2, 16)));
        lbTituloTabla.setForeground(new Color(Integer.parseInt(color3, 16)));
    }

   /* private String fecha() {
        Calendar Calendario = Calendar.getInstance();

        String anho = Integer.toString(Calendario.get(Calendar.YEAR));
        String mes = Integer.toString(Calendario.get(Calendar.MONTH) + 1);
        String dia = Integer.toString(Calendario.get(Calendar.DATE));

        return (dia + "/" + "0" + mes + "/" + anho);
    }*/

    private void llenarTabla() {
        DefaultTableModel miModelo = (DefaultTableModel) this.tblUsuarios.getModel();

        ArrayList<Object[]> data = new ArrayList<>();

        estArticulo p = cab;

        while (p != null) {
            String[] datos = {p.lugar, p.fecha, p.horaF, p.horaI};
            data.add(datos);
            p = p.liga;
        }

        for (int i = 0; i < data.size(); i++) {
            miModelo.addRow(data.get(i));
        }

        tblUsuarios.setRowHeight(25);
    }

    public void botones(boolean a) {

        btnModificar.setEnabled(a);
        btnEliminar.setEnabled(a);
    }

    private void camposArticulos() {
        txtLugar.setText("");
        txtEstado.setText("Activo");
        txtFe.setText("");
        txtDescripcion.setText("");
        txtHoraI.setText("");
        TxtHT.setText("");
       

        TxtHT.setEditable(true);
        txtFe.setEditable(true);
        txtLugar.setEditable(true);

        grupoTipo.setSelected(null, false);

        
    }

    private void cargarDatos() 
    {
        try {
            File f = new File("E:/articulos.in");
            BufferedReader entrada;
            entrada = new BufferedReader(new FileReader(f));
            String[] nodos = entrada.readLine().split("---"), valores;

            estArticulo p;

            for (int i = 0; i < nodos.length; i++) {
                p = new estArticulo();

                if (p == null) {
                    System.out.println("Memoria llena");
                } else {
                    valores = nodos[i].split(",");

                    p.lugar = valores[0];
                    p.horaF= valores[1];
                    p.horaI = valores[2];
                    p.fecha= valores[3];
                    p.titulo = valores[4];
                      p.descripcion= valores[5];
                    p.estado = valores[6];
                  

                    if (cab == null) {
                        cab = p;
                    } else {
                        ult.liga = p;
                    }
                    ult = p;
                }
            }
        } catch (IOException e) {
            System.out.println("Error: " + e);
        }
    }

    private estArticulo consultarArticulo(String articulo) {
        estArticulo p = cab;

        while (p != null) {
            if (p.lugar.equals(articulo)) {
                return p;
            }
            p = p.liga;
        }
        return null;
    }

    private void nuevoArticulo(String registro) {
        File f;
        f = new File("E:/articulos.in");
        try {
            FileWriter fw = new FileWriter(f, true);
            fw.append(registro);
            fw.close();
        } catch (IOException e) {
        };
    }
    
    
        private void modRegistro() 
    {
        estArticulo p = cab;
        String registro = "---";
        
        File f = new File("E:/articulos.in");
        
        try {
            Writer output = new BufferedWriter(new FileWriter(f));
            try {
                output.write("");
            }
            finally {
                output.close();
            }
        }
        catch (IOException e){}
        
        if (p == null) {
            System.out.println("Lista vacia");
        } 
        else {
            while (p != null) {
                
                if (p == cab){
                    registro = "";
                }
                
                registro += p.lugar + "," +p.titulo+","+ p.fecha + "," + p.horaI + "," + p.horaF
                        + "," + p.descripcion+ "," + "Activo" ;
                
                nuevoArticulo(registro);
                registro = "---";
                p = p.liga;
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtHT;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbImpresora;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbModelo;
    private javax.swing.JLabel lbNumSerie;
    private javax.swing.JLabel lbNumSerie1;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTituloArt;
    private javax.swing.JLabel lbTituloTabla;
    private javax.swing.JPanel pnlArticulo;
    private javax.swing.JPanel pnlBotonesArticulo;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JPanel pnlTituloArt;
    private javax.swing.JPanel pnlTituloTabla;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTabbedPane tbpSolicitud;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFe;
    private javax.swing.JTextField txtFiltrador;
    private javax.swing.JTextField txtHoraI;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
